### ISSUE TITLE
DWD weather data missing

### ISSUE THREAD

**Issue by lweidmueller** [FL550/dwd_weather#100]
Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

## Describe the bug
No data available

## My Station
01475

## Debug log

2023-10-24 00:12:13.670 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from WebKit 605.1.15 on Mac OS 10.15.7
Error: Weather entity "weather.dwd_weather_mittelnkirchen_hohen" does not support daily forecasts.
subscribeForecastEvents (/hacsfiles/clock-weather-card/clock-weather-card.js:242:6674)
connectedCallback (/hacsfiles/clock-weather-card/clock-weather-card.js:196:122)
this (src/scoped-custom-element-registry.js:248:47)
appendChild ([native code]::)
_createPanel (src/layouts/hass-router-page.ts:318:21)
loadProm.then( (src/layouts/hass-router-page.ts:215:10)
2023-10-24 00:12:14.089 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from WebKit 605.1.15 on Mac OS 10.15.7
Error: Weather entity "weather.dwd_weather_mittelnkirchen_hohen" does not support daily forecasts.
subscribeForecastEvents (/hacsfiles/clock-weather-card/clock-weather-card.js:242:6674)
connectedCallback (/hacsfiles/clock-weather-card/clock-weather-card.js:196:122)
this (src/scoped-custom-element-registry.js:248:47)
appendChild ([native code]::)
document.createElement (src/panels/lovelace/hui-root.ts:943:21)
2023-10-24 00:12:36.174 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for 01475 data in 0.001 seconds (success: True)
2023-10-24 00:13:36.174 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for 01475 data in 0.001 seconds (success: True)
2023-10-24 00:14:36.174 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for 01475 data in 0.001 seconds (success: True)
```

**Comment by MadMacMad** [comment]
{{ state_attr('weather.bad_bentheim','temperature') | default('0') }} -> works
{{ state_attr('weather.bad_bentheim','forecast')[0].condition | default('0')  }} -> doesn't work 
forecast is broken since last updates...
hope it's easy to fix ;-)
thx
M.

**Comment by lweidmueller** [comment]
OK, give me a hint for testing.
thx L

**Comment by MadMacMad** [comment]
here is a work around...
was not easy to find out ...
but this is a safe way also for future... since HA updated the api...

Automation:
`alias: Wetter Aktualisierung
description: Aktualisiert die Wetterdaten
trigger:
  - platform: time_pattern
    hours: "/1"
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_template_reloaded
condition: []
action:
  - service: weather.get_forecast
    data:
      type: daily
    target:
      entity_id: weather.bad_bentheim
    response_variable: weather_data
  - service: system_log.write
    data:
      message: "Debug: weather_data: {{ weather_data }}"
      level: warning
  - alias: Set Weather Data
    repeat:
      count: "{{ [weather_data['forecast']|length, 8]|min }}"
      sequence:
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_forecast_temp_day{{ repeat.index }}_max"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['temperature'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_forecast_temp_day{{ repeat.index }}_min"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['templow'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_condition_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['condition'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_precipitation_probability_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['precipitation_probability'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_precipitation_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['precipitation'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_wind_bearing_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['wind_bearing'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_wind_gusts_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['wind_gusts'] }}"
        - service: input_text.set_value
          target:
            entity_id: "input_text.dwd_weather_wind_speed_{{ repeat.index }}d"
          data:
            value: "{{ weather_data['forecast'][repeat.index]['wind_speed'] }}"
mode: single
`

and in config you need to add:

`input_text:
dwd_weather_condition_0d:
    name: DWD Forecast Day 0
dwd_weather_precipitation_probability_0d:
    name: DWD Precipitation Probability Day 0
dwd_weather_precipitation_0d:
    name: DWD Precipitation Day 0
dwd_weather_wind_bearing_0d:
    name: DWD Wind Bearing Day 0
dwd_weather_wind_gusts_0d:
    name: DWD Wind Gusts Day 0
dwd_weather_wind_speed_0d:
    name: DWD Wind Speed Day 0
dwd_weather_forecast_temp_day0_max:
    name: DWD Forecast Temp Day 0 Max
dwd_weather_forecast_temp_day0_min:
    name: DWD Forecast Temp Day 0 Min
`->you need to add day 0-8 for each... 

and if you need a Sensor for Platinum Weather Card or other:
`template:
  - sensor:
      - name: "DWD Bad Bentheim Vorhersage Heute Max"
        unique_id: dwd_bad_bentheim_forecast_today_max
        unit_of_measurement: "°C"
        state: "{{ states('input_text.dwd_weather_forecast_temp_day0_max') }}"
  - sensor:
      - name: "DWD Bad Bentheim Vorhersage Heute Min"
        unique_id: dwd_bad_bentheim_forecast_today_min
        unit_of_measurement: "°C"
        state: "{{ states('input_text.dwd_weather_forecast_temp_day0_min') }}"`

it's some work... but safe and future proof... you only need to change entity_id: weather.bad_bentheim to another like the build in for testing... all weather station that work with same format and are supported by - service: weather.get_forecast should work... ;-)

**Comment by lweidmueller** [comment]
OK, create automation and change to YAML editor. copy and paste and try to set right spaces on left side.
On save I get the error as shown in the screenshot.
<img width="709" alt="screenshot 2023-10-28 22 26 28" src="https://github.com/FL550/dwd_weather/assets/47306122/2ac30b10-a858-4b8a-928a-5151cdb6c13a">

whats wrong

**Comment by FL550** [comment]
I just confirmed your station 'mittelnkirchen' produces a daily forecast. So this more likely an error in the clock-weather-card.

**Comment by lweidmueller** [comment]
I just delete  (cleared files) and reinstall (there were new versions yesterday) and adapt my dashboard 
Now ist works!

Thanks for support

**Comment by lweidmueller** [comment]
the end
