### ISSUE TITLE
Odd values for humidity

### ISSUE THREAD

**Issue by fl0x53** [FL550/dwd_weather#103]
## Version of home_assistant
Home Assistant 2023.10.5 / official docker image

## Version of the custom_component
2.0.9

## Describe the bug
since Oct. 24th the entity for humidity (Station 10763) is showing strange values (>100%):
![grafik](https://github.com/FL550/dwd_weather/assets/70536684/2663a6eb-ced2-4b03-8135-0fb140a12137)

Just added another station (P257), that is now also showing those strange values.

`simple_dwd_weatherforecast` is getting correct values. And Forecast data OrderedDict (see log) is also holding correct values. 🤔 

(I could not find any updates etc. that have anything to do with the above date.)

## Debug log
[home-assistant_dwd_weather_2023-10-30.log](https://github.com/FL550/dwd_weather/files/13209198/home-assistant_dwd_weather_2023-10-30.log)
couldn't find a clue 🤷

**Comment by fl0x53** [comment]
my bad. 🤦
Found the error. Was experimenting with the python site libs to fix the irradiance issue

**Comment by FL550** [comment]
Ah, ok. Thanks for checking again :)
