### ISSUE TITLE
Old weather forecast complain

### ISSUE THREAD

**Issue by schlaufon** [FL550/dwd_weather#106]
![image](https://github.com/FL550/dwd_weather/assets/126504679/7dfee9cd-41d2-425a-a181-9faeebc8a50b)

**Comment by FL550** [comment]
Thanks for reporting!

**Comment by FL550** [comment]
Which version are you on? This was removed already in [v2.0.1](https://github.com/FL550/dwd_weather/tree/v2.0.1).

**Comment by schlaufon** [comment]
> Which version are you on? This was removed already in [v2.0.1](https://github.com/FL550/dwd_weather/tree/v2.0.1).

exactly that v2.01. was my version

**Comment by FL550** [comment]
Then please update to the latest version and reopen this issue if the situation persists.
