### ISSUE TITLE
Support UVINDEX

### ISSUE THREAD

**Issue by misery** [FL550/dwd_weather#108]
**Is your feature request related to a problem? Please describe.**
I like to have a forecast of the UVINDEX from current day. 

**Describe the solution you'd like**
Provide sensors to show UVINDEX like.
* Current UV
* Max UV of this day
* Min UV of this day

**Comment by FL550** [comment]
I found some UV index data from DWD. However, these are only available as a single value for the whole day

**Comment by misery** [comment]
Thanks, yes. I looked into the app. Seems one value per day is correct.

**Comment by FL550** [comment]
It is now implemented.

**Comment by panhans** [comment]
Hey, I am happy with the forecast. I am using the UV-Index to notify for sun blocker. But today the home assistant integration shows an index of 3 but the dwd android app displays just max 2. Is there a way to evaluate this differences?

**Comment by FL550** [comment]
@panhans Yes, you could evaluate the raw data here: https://opendata.dwd.de/climate_environment/health/alerts/uvi.json

The integration automatically picks the closest location based on your configuration.
