### ISSUE TITLE
Integration does not appear in HA

### ISSUE THREAD

**Issue by ldoench** [FL550/dwd_weather#11]
## Version of home_assistant
Home Assistant 2021.1.4

## Version of the custom_component
v1.1.9

## Describe the bug
I installed the Integration in HACS
<img src="https://user-images.githubusercontent.com/12457264/105109445-d511d800-5abc-11eb-8dab-e9f1666e9855.png" width="500">
But it does not appear in the Integrations section of HA:
<img src="https://user-images.githubusercontent.com/12457264/105108773-481a4f00-5abb-11eb-8660-e9d2614848b3.png" width="400">

## Debug log

Nothing DWD related appearing

**Comment by ldoench** [comment]
After removing the docker container and re adding it, it suddenly appeared. 
Already tried restarting and deleting cache so no idea, what caused this bug to disapear

**Comment by FL550** [comment]
I'm sorry for my late reply! I'm glad, the bug resolved itself.

**Comment by DeepCoreSystem** [comment]
@ldoench which docker container do you mean??
 
> After removing the docker container and re adding it, it suddenly appeared.
> Already tried restarting and deleting cache so no idea, what caused this bug to disapear

**Comment by ldoench** [comment]
> @ldoench which docker container do you mean??
> 
> > After removing the docker container and re adding it, it suddenly appeared.
> > Already tried restarting and deleting cache so no idea, what caused this bug to disapear

I installed it on RPi 3 with this tutorial: https://www.home-assistant.io/docs/installation/docker/
