### ISSUE TITLE
Wrong area in Weather report after update to v2.0.13

### ISSUE THREAD

**Issue by PeterHoge** [FL550/dwd_weather#111]
HA: 2023.11.3
Update dwd_weather from ? to 2.0.13

Station G005 Berlin-Marzahn

Before: Wetter- und Warnlage für Brandenburg und Berlin
Now (wrong): Wetter- und Warnlage für Bayern

Card: {{ state_attr("sensor.berlin_marzahn_wetterbericht", "data") }}

The other enities are OK.

I have tried this on 3 machines.

Thank you

![Wetter_before](https://github.com/FL550/dwd_weather/assets/53821873/fe3fcd54-dc05-43c1-bb23-86cc456c8154)
![Wetter_2 0 13](https://github.com/FL550/dwd_weather/assets/53821873/40282952-7c19-42ac-9a26-b5dd8ff1e886)

**Comment by FL550** [comment]
I've found the error. Thanks for reporting. I will soon release a new version which fixes this!
