### ISSUE TITLE
504 Gateway Time-out during initial configuration

### ISSUE THREAD

**Issue by PiperNigrum** [FL550/dwd_weather#114]
## Version of home_assistant
Core: 2023.12.3
Supervisor: 2023.12.0
Operating System: 11.2
Frontend: 20231208.2

Maschine: armv7 (RP2) with Home Assistant OS

## Version of the custom_component
v2.0.13 (current)

## Describe the bug
I've successfully installed the customer component and rebooted my system.
If I want to install the Integration the configuration flow crashes with following message:
![Error](https://github.com/FL550/dwd_weather/assets/16720769/13c11d80-3fcf-417b-9603-e3c7cdc0647d)

## Debug log

```text

Add your logs here.

```

**Comment by FL550** [comment]
Hi, how was the error fixed for you?

**Comment by PiperNigrum** [comment]
> Hi, how was the error fixed for you?

I tried it today and it worked.

**Comment by relrod** [comment]
I'm seeing this too :(

![image](https://github.com/FL550/dwd_weather/assets/43930/4f331717-d58e-4b38-9c26-b62541289001)
