### ISSUE TITLE
weather.get_forecasts ignores wind_speed_unit

### ISSUE THREAD

**Issue by ministryofsillywalks** [FL550/dwd_weather#116]
## Version of home_assistant

2023.12.3

## Version of the custom_component

2.0.13

## Describe the bug
Looking at the attributes of the weather entity wind speed is shown in km/h (as desired and set)
![image](https://github.com/FL550/dwd_weather/assets/10544895/cd35b5fa-4bf9-4894-9a76-3724e8f17450)

However when calling the the weather.get_forecasts service it returns a completely different wind speed. Maybe ft/s? I really don't know what measurement this is. (both for hourly and daily forecasts)
![image](https://github.com/FL550/dwd_weather/assets/10544895/319ee836-a61d-460d-97d1-9343f746795b)

I'm not sure if this is a dwd integration or a home assistant bug. I thoght I'd post here first before posting over at home assistant issues.

**Comment by FL550** [comment]
Hi, thanks for reporting. This is an error in my integration, so you are correct here. 

I'll fix this as soon as I can.

Best regards
