### ISSUE TITLE
Hourly Forecast not updated/refreshed in cards

### ISSUE THREAD

**Issue by somansch** [FL550/dwd_weather#117]
## Version of home_assistant
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

## Version of the custom_component
v2.1.0

## Describe the bug
I'm using the hourly forecast info inside custom:hourly-weather card. It's shown on a info display on the main dashboard. I've identified, that it's not updating the content inside the card automatically. I've done some testing to identify the root cause. So, I created one dashboard to show in parallel two different cards (the builtin "weather-forecast" and "custom:hourly-weather) and also two different weather entities ("DWD" and "OpenWeatherMap") + the actual time:
<img width="1233" alt="2024-01-10_11-27-08" src="https://github.com/FL550/dwd_weather/assets/47367267/fed73932-21b2-4276-8027-f6a4ab7bcbf3">
After one hour, only the content of "OpenWeatherMap" is updated automatically in both cards:
<img width="1234" alt="2024-01-10_12-15-40" src="https://github.com/FL550/dwd_weather/assets/47367267/6e60e99d-e186-4e8d-b774-e0ea9679b438">
You need to refresh/reload the page on the affected device **or** any other device to get the data updated:
<img width="1226" alt="2024-01-10_12-16-05" src="https://github.com/FL550/dwd_weather/assets/47367267/0f13ee87-984b-4251-b2f2-e15b0189104b">

**Comment by FL550** [comment]
Hm, strange. I'll look into this tomorrow.

Thanks for reporting!

**Comment by FL550** [comment]
This is now hopefully fixed. Can you please confirm this?

**Comment by somansch** [comment]
Thanks for your fast take on this. I just tested v2.1.1. Unfortunately, no change in this behavior. If you test a fix, it's important that you have not opened another browser or app with HA as this will trigger an update.

**Comment by Failure404** [comment]
I don't know if the problem I am experiencing relates to this thread here, but I am using the same hourly weather card and I am getting lots of
 "days_from_today must be between 0 and 2" 
error messages in the HA log when the card gets loaded.
However, the card looks perfectly fine and shows what it is supposed to show.
This error only appears when using the DWD weather entity, other weather providers don't generate that error.

**Comment by FL550** [comment]
@Failure404 days_from_today is not an attribute which is specified in a weather entity: [link](https://developers.home-assistant.io/docs/core/entity/weather/#weather-forecasts), so I don't know where this is coming from.

**Comment by FL550** [comment]
I think I have found the issue. However this needs probably done time, because I have to rework the data update mechanism. I'll keep you informed.

**Comment by FL550** [comment]
Found the issue and implemented a fix. New version is out.

**Comment by somansch** [comment]
Thanks! Just tested the new version and I can confirm - it's fixed.
