### ISSUE TITLE
Invalid escape sequence (2024.2.0b0)

### ISSUE THREAD

**Issue by elcajon** [FL550/dwd_weather#119]
## Version of home_assistant

2024.2.0b0
## Version of the custom_component

v2.1.1
## Describe the bug
The following error message appears in the log since the latest beta version.

## Debug log

```text

Logger: py.warnings
Source: loader.py:864
First occurred: 07:57:18 (1 occurrences)
Last logged: 07:57:18

/config/custom_components/dwd_weather/sensor.py:300: SyntaxWarning: invalid escape sequence '\w' "\w+, \d{2}\.\d{2}\.\d{2}, \d{2}:\d{2}",

```

**Comment by elcajon** [comment]
The warning has disappeared since the last beta, so I'm closing the issue.

Sorry for bothering!

**Comment by FL550** [comment]
Ok, good to know. I had planned to have a look into this this weekend.

And thanks for reporting!
