### ISSUE TITLE
Sun Duration sensor looses information until current hour (past lost)

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [FL550/dwd_weather#120]
Hi

I am using apexcharts-card to visualize the sun duration information given my the integration.
I want to show the sun duraction per hour over the entire day. 
I noticed that the graph loses data and only starts at the current hour. 

This seems to be because the integration seems only to write the data from DWD to the sensor starting the current hour. So when we reach the next hour, the previous data is cleared out, hence the information about the prior time of the current day is lost.

I would assume this is intended to clean up the sensor to not have it grow and grow, but it would be great if at least the entire day is kept until the day actually is over. Maybe I misunderstood whats going on...?

Best Regards

|| Integration: v2.1.1 || HA 2024.1.6 ||

**Comment by FL550** [comment]
Hi,

this is normal behaviour as the sensor value only represents the actual hour. However you might achive what you are trying by using the history values which are recorded by Homeassistant. Have a look [here](https://www.home-assistant.io/integrations/history/) and [here](https://www.home-assistant.io/integrations/history_stats/).

Best regards

**Comment by Sesshoumaru-sama** [comment]
His history graph shows the data up to the hour before the currrent hour, plus the sensor itself there should be all data.
But how to "fuse" this two? Its like only these two togather form the entire day. Is it possible to have to entities as source for one graph series? Is the history an entity in first place?

**Comment by FL550** [comment]
@Sesshoumaru-sama It might be possible to achieve this with a template sensor.
