### ISSUE TITLE
async_forward_entry_setup call warning for integration dwd_weather

### ISSUE THREAD

**Issue by jf-64** [FL550/dwd_weather#133]
## Version of home_assistant

Home Assistant

Core
2024.7.2
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

## Version of the custom_component

dwd_weather v2.1.3

## Describe the bug
Setup > System > Protocols calls for reporting an issue after HA was restarted:

> Logger: homeassistant.helpers.frame
> Quelle: helpers/frame.py:151
> Erstmals aufgetreten: 08:40:45 (2 Vorkommnisse)
> Zuletzt protokolliert: 08:40:45
> 
> Detected code that calls async_forward_entry_setup for integration dwd_weather with title: P333: Nuernberg-Netzstall and entry_id: c88e62853de094b1dd9c7c464fbb3ea5, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

## Debug log

```text

Add your logs here.

```

**Comment by FL550** [comment]
Thanks for reporting.

This was fixed in the latest version 2.1.4.
