### ISSUE TITLE
DWD Weather condition: wrong history (numerical instead of textual)

### ISSUE THREAD

**Issue by jf-64** [FL550/dwd_weather#134]
## Version of home_assistant

Home Assistant

Core
2024.7.3
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

## Version of the custom_component

v2.1.4

## Describe the bug
A clear and concise description of what the bug or error is and when it happens.

Steps to reproduce the issue:
1. Go to Setup > Entities
2. Select the condition (in German 'Wetterzustand') entity
3. In the dialog you can see the the condition (e.g. "sunny"), but also the text "No statistics found"
4. Click on Show more (in German 'Mehr anzeigen')
5. A numeric and empty graph will be opened,  instead of the textual history

## Debug log

```text

Add your logs here.

```
![image](https://github.com/user-attachments/assets/660ac018-3995-49e0-a06e-dea064a0077c)
![image](https://github.com/user-attachments/assets/d3bc38ef-7086-49bf-9a70-43b9dbc093b4)
[home-assistant_dwd_weather_2024-07-24T17-49-44.361Z.log](https://github.com/user-attachments/files/16365817/home-assistant_dwd_weather_2024-07-24T17-49-44.361Z.log)

**Comment by FL550** [comment]
Thanks for reporting. However, I don't think this is something I can change. The weather condition is always reported as a string, so there shouldn't be numerical values available at any time.

**Comment by jf-64** [comment]
OpenWheather can do it correctly like this:
![image](https://github.com/user-attachments/assets/29e535a2-5760-41df-9b60-08c437e61f66)

**Comment by FL550** [comment]
Yes, I know. This integration can as well.

The history is nothing an integration takes care of, it's Homeassistant itself. So I guess your instance thinks this should be a numerical value but in fact it's not as displayed in the state. 

I don't know where your instance got the numerical value in the first place, but you have to clean your history or adjust the internal settings of this sensor.
