### ISSUE TITLE
Examples for charts

### ISSUE THREAD

**Issue by tebbbb** [FL550/dwd_weather#137]
Can you please add some code examples for weather charts (especially for regions)?

**Comment by FL550** [comment]
There is no user code involved in the weather charts. You can configure everything via the Homeassistant UI. Just select "weather chart" during setup of a new entity.

**Comment by Samurai1201** [comment]
I cant find it anywhere in my ui...
Can you maybe point me the right direction? Or like give me the base raw config for the card?

Thanks a lot for your work

**Comment by FL550** [comment]
Have you done the setup of the map? 
You have to go to integrations, add DWD and in the following setup dialog select the map. If all was configured, you have a new camera entity within HA, which you can add to a picture glance element. 

![image](https://github.com/user-attachments/assets/6ea011a9-017d-4f1e-97e0-bc13c90b7777)

![image](https://github.com/user-attachments/assets/1b6a4d6b-98e6-43ce-a3d2-4a4711e5e876)

![image](https://github.com/user-attachments/assets/66de8e53-1d7f-436f-ae09-3f5323dcd6bf)

![image](https://github.com/user-attachments/assets/7fc41ae5-e945-44ca-a32c-812a0c1d88e9)

**Comment by nyphis** [comment]
@FL550
Thanks for pointing out - I was also lot with the precipation map
May be it is a hint in the readme worth on how to get it working - especially if your DWD integration setup has been done long ago

**Comment by nyphis** [comment]
Just an additional hint ...

If you select `map_custom` you're presented with the "standard" HA location popup.
For German users this will result in an error.
You will have to replace the commas in the longitude / latitude fields by points to get it working.

![grafik](https://github.com/user-attachments/assets/5286fd5d-8e64-4fba-a10e-2b4c44076855)

**Comment by FL550** [comment]
Yes maybe it is time to give the Readme more love.

@nyphis This is strange, as the prefilled values are retrieved directly from the HA user config. I'll check this.

**Comment by Samurai1201** [comment]
Thanks a lot!

Been a while since i first set up this integration, so I didnt realize there was another setup option

my problem is solved, thanks a lot
