### ISSUE TITLE
Coordinates not prefilled

### ISSUE THREAD

**Issue by FL550** [FL550/dwd_weather#141]
If you select `map_custom` you're presented with the "standard" HA location popup.
For German users this will result in an error.
You will have to replace the commas in the longitude / latitude fields by points to get it working.

![grafik](https://github.com/user-attachments/assets/5286fd5d-8e64-4fba-a10e-2b4c44076855)

_Originally posted by @nyphis in https://github.com/FL550/dwd_weather/issues/137#issuecomment-2333341825_

**Comment by nyphis** [comment]
Basically I really like that the coordinates are prefilled since most of the users want to have at least a map for their home, won't they?

The problem is, that the comma causes an issue - maybe that could be handled / replaced by the integration setup itself?

**Comment by FL550** [comment]
The problem is, that there should be no comma in the fields. I'll add an extra check which replaces possibly? wrong values.

**Comment by FL550** [comment]
@nyphis 
Ok, I have to correct myself: The data is automatically prefilled by Homeassistant based on the configured location. Unfortunately I am unable to correct the values in the code. So I guess there is a small configuration error on your side. 

Can you please check your `configuration.yaml` if there is a location configured? And if so, if there is a comma or dot in the values?

**Comment by nyphis** [comment]
@FL550
There's no location configured in my `configuration.yaml` or any other configuration file.

**Comment by FL550** [comment]
@nyphis I can't reproduce this in any possible combination of configuration of the location I can think of. Maybe you have setup your HA a long time ago and there has been a change in the format? I'll close this for now, as I can't adjust this error in my code and is probably a configuration issue. Feel free to reopen this, if you find more information on this.
