### ISSUE TITLE
map kreise and gemeinden are in the forground instead of the background

### ISSUE THREAD

**Issue by tohcnam** [FL550/dwd_weather#145]
## Version of home_assistant
2024.9.1

## Version of the custom_component
2.1.7

## Describe the bug
Choosing a weather map I can define what should be the background for the map. 'bundeslaneder' and 'laender' is working as expected, but 'gemeinden' and 'kreise' are showing the map in the forground instaed of the background. With this, I can not see the actual map. See scrennshot of the background image 'kreise'. 
![image](https://github.com/user-attachments/assets/fdba47f4-c23c-484b-8730-a0b06c7757c9)

**Comment by FL550** [comment]
Thanks for reporting! I'll fix this as soon as possible.

**Comment by FL550** [comment]
@ahessling Thanks for troubleshooting! I know where this issue arises from. Half a year ago, I was notified, that the order of layers was wrong for the satellite image: https://github.com/FL550/simple_dwd_weatherforecast/issues/21 . My error was, to implement this for all layers, not realizing there were layers with different transparencies. I'll implement a version, which checks the correct order for each combination and release it probably today, latest tomorrow. 

Viele Grüße zurück!

**Comment by FL550** [comment]
This now fixed with the latest version. Thanks for reporting this!
