### ISSUE TITLE
Add Evaporation as available field (PEvap)

### ISSUE THREAD

**Issue by timmost** [FL550/dwd_weather#146]
Would it be possible to add the Evaporation data from the DWD forecast to the data set ? 
This data is available under the DWD data set:
`
<MetElement>
<ShortName>PEvap</ShortName>
<UnitOfMeasurement>kg / m2</UnitOfMeasurement>
<Description>Potential evapotranspiration within the last 24 hours</Description>
</MetElement>
`
There are also forecast values for the next days available. Would be great to use to control and steer the garden watering system.
Thx a lot for considering!

**Comment by FL550** [comment]
I'll definitely have a look at this. I'll keep you posted!

**Comment by FL550** [comment]
I've checked the data you have mentioned. The value is only available in the hourly data, which is no showstopper. However I am not sure how to implement this correctly. 

The issue is, that the values are based on the last 24 hours and are only provided once per day at 06:00Z. So if I create a sensor, at which time should I change the values? Also at 06:00Z? This would definitely need some explanation.

**Comment by timmost** [comment]
Hi there,

The relevant value is that of 6:00 in the morning. I think that there is
also a forecast value for the next days, always updated at 6:00.

 I am new to Home Assistant, so need to learn this (coming from a large
FHEM installation)

There is a module at FHEM that might help:
https://github.com/jnsbyr/fhem/blob/master/FHEM/55_DWD_OpenData.pm
There is also a wiki chapter:
https://wiki.fhem.de/wiki/DWD_OpenData

Let me know if you<I can help with testing etc..
Thank you for your help!

Best Timmo


FL550 ***@***.***> schrieb am Mi. 18. Sept. 2024 um 14:01:

**Comment by FL550** [comment]
Yes, there is only the value at 6:00Z available, so we need to use this. And yes, the data contains the forecast for the next days as well. However the question stays the same:

> The issue is, that the values are based on the last 24 hours and are only provided once per day at 06:00Z. So if I create a sensor, at which time should I change the values? Also at 06:00Z? This would definitely need some explanation.

**Comment by timmost** [comment]
Hi there

I would say that a change of value at 6:00 after the update makes most
sense…
Best Timmo



FL550 ***@***.***> schrieb am Do. 19. Sept. 2024 um 19:01:

**Comment by FL550** [comment]
It's included now in the latest version.
