### ISSUE TITLE
Building Failure on 2024.10dev

### ISSUE THREAD

**Issue by elcajon** [FL550/dwd_weather#148]
## Version of home_assistant

2024.10dev (latest nightly)

running on latest HAOS (nightly)

## Version of the custom_component

latest

## Describe the bug

Not able to setup the custom integration, fails with error below. Also not sure if it is related to your pypi base package or this custom integration to be honest.

## Debug log

Unable to install package simple_dwd_weatherforecast==2.1.4: error: Failed to prepare distributions Caused by: Failed to fetch wheel: stream-inflate==0.0.30 Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1 --- stdout: running bdist_wheel running build running build_py copying stream_inflate.py -> build/lib.linux-x86_64-cpython-312 running egg_info writing stream_inflate.egg-info/PKG-INFO writing dependency_links to stream_inflate.egg-info/dependency_links.txt writing requirements to stream_inflate.egg-info/requires.txt writing top-level names to stream_inflate.egg-info/top_level.txt reading manifest file 'stream_inflate.egg-info/SOURCES.txt' adding license file 'LICENSE' writing manifest file 'stream_inflate.egg-info/SOURCES.txt' running build_ext building 'stream_inflate' extension gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/root/.cache/uv/builds-v0/.tmpn0sQqp/include -I/usr/local/include/python3.12 -c stream_inflate.c -o build/temp.linux-x86_64-cpython-312/stream_inflate.o --- stderr: /root/.cache/uv/builds-v0/.tmpn0sQqp/lib/python3.12/site-packages/setuptools/dist.py:294: InformationOnly: Normalizing 'v0.0.30' to '0.0.30' self.metadata.version = self._normalize_version(self.metadata.version) error: command 'gcc' failed: No such file or directory ---

**Comment by FL550** [comment]
Thanks for reporting. I guess its because there was a new version released today, which hasn't yet been updated in your mirror: https://pypi.org/project/stream-inflate/

I use httpx in my package which itself uses stream-inflate. So please try this again in a few hours.

**Comment by elcajon** [comment]
I have been seeing this bug for a few days now, but there have also been almost daily updates from stream-inflate over the last week. I'll keep an eye on it, it's still a while until the next HA release... I'll let you know if anything changes.

**Comment by FL550** [comment]
Oh okay. I mean I can pin the version if the updates are too frequent. Would this be an option for you?

**Comment by elcajon** [comment]
Since the last update it works since today, I guess you were right about the mirror error. Thanks!
