### ISSUE TITLE
Invalid Date 

### ISSUE THREAD

**Issue by Krocko** [FL550/dwd_weather#15]
After latest update the forecast don‘t work anymore. 
![79ED33C5-2E0D-46AD-98F2-F199BC9EDF70](https://user-images.githubusercontent.com/29394115/109397803-e27e7580-7938-11eb-9f79-f6b701cf8a57.jpeg)
![646C82B6-0638-4F38-8163-CDBF6FC33741](https://user-images.githubusercontent.com/29394115/109397804-e4e0cf80-7938-11eb-9187-520ffd6b261f.jpeg)

**Comment by FL550** [comment]
Can you please show me the entity from the developer pane?

**Comment by Krocko** [comment]
Sure:
![image](https://user-images.githubusercontent.com/29394115/109399094-faf28e00-7940-11eb-8326-89c687abe5cd.png)

**Comment by FL550** [comment]
Hm, strange. The dates look correct. On my side everything is working fine. Do you use any special card for display?

**Comment by FL550** [comment]
![Screenshot 2021-02-27 212335](https://user-images.githubusercontent.com/36160004/109399290-4b1e2000-7942-11eb-8a94-728ba53fb5ed.png)
![Screenshot 2021-02-27 212405](https://user-images.githubusercontent.com/36160004/109399291-4bb6b680-7942-11eb-8d90-7eab2c4056cf.png)
![Screenshot 2021-02-27 212424](https://user-images.githubusercontent.com/36160004/109399292-4bb6b680-7942-11eb-8613-e88240e09299.png)

**Comment by Krocko** [comment]
It is `custom:weather-card`
But also with the standard card I have this error.
![image](https://user-images.githubusercontent.com/29394115/109399525-9d137580-7943-11eb-81ac-f2a6df978ba1.jpeg)
With v1.1.9 all is working.

**Comment by Krocko** [comment]
If I write a `T` between the date and the time in the developertools, it is working. Can you change something in the timestamp, to get the `T` automatically?
![image](https://user-images.githubusercontent.com/29394115/109410910-9fef8400-799e-11eb-99d5-4320cf00ed03.png)

**Comment by FL550** [comment]
Sure! I'll bring an update later this day.

**Comment by FL550** [comment]
This should be corrected with the latest update. Thanks for your report and solution hint!
