### ISSUE TITLE
sensor Probability of precipitation missing

### ISSUE THREAD

**Issue by roandreas** [FL550/dwd_weather#153]
Dear Team,

since serveral weeks my precipitation sensor (Niederschlagswahrscheinlichkeit) from Köln Stammheim is missing.

DWD v2.1.11
HA 2024.9.3

Before it was sensor.koeln_stammheim_niederschlagswahrscheinlichkeit

Thx for feedback.

Robert

**Comment by FL550** [comment]
Hello Robert,

do you have the hourly update enabled?

**Comment by roandreas** [comment]
Yes, its activated to force hourly updates

**Comment by FL550** [comment]
Ok, I found the error. This was introduced a year ago and nobody noticed until now. So thanks for reporting.

**Comment by FL550** [comment]
This information is not available in the hourly update unfortunately.

**Comment by FL550** [comment]
@roandreas You can add the same station again with a different name and use the normal update to get this value again.
