### ISSUE TITLE
Error during integration setup

### ISSUE THREAD

**Issue by ReefjunkyGMX** [FL550/dwd_weather#159]
During setup of DWD integration the following error message apears:
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

## Version of home_assistant
Core
2024.10.3
Supervisor
2024.10.2
Operating System
13.2
Frontend
20241002.3

## Version of the custom_component
newest version of integration used

## Debug log

not available

**Comment by sphings79** [comment]
Same over here. Already tried v.2.1.18. Same error.

**Comment by FL550** [comment]
Please see #159. It has the same cause.

**Comment by hoxm90** [comment]
I have the same problem. Notification after update to Core 2024.10.3: "Invalid config
The following integrations and platforms could not be set up:
 [dwd_weather]
 - Please check your config and [logs]"

**Comment by sphings79** [comment]
> Please see #159. It has the same cause.

This is #159 🤷🏼

**Comment by FL550** [comment]
My bad, I'm on mobile. I mean #157

**Comment by hoxm90** [comment]
Thank you very much, the DWD update to version v2.1.19 has solved the problem, everything is working perfectly again for me. I will buy you a coffee... ;-)

**Comment by FL550** [comment]
@hoxm90 Thanks for reporting and glad to hear that. And thank you for the coffee. I'll enjoy it during the next coding session. Currently I'm on vacation 😉

**Comment by hoxm90** [comment]
No problem, have a nice vacation! 😉

**Comment by ReefjunkyGMX** [comment]
Works after update. Thanks

**Comment by ReefjunkyGMX** [comment]
Done

**Comment by baloo-gh** [comment]
Unfortunately the latest version doesn't work for me. Had the same issue as also described in 155 and 159, though I cannot get it to work again. Even a downgrade of the core doesn't make it work. I guess the unzip library on my system is already ahead of the version the bug fix was freezing this wonderful piece of work. 

Hope a future version will work again as I am using the data from this to override my heating system, generating quite a substantial amount of savings through this :-)
