### ISSUE TITLE
No longer working after installing update

### ISSUE THREAD

**Issue by andreas-2017** [FL550/dwd_weather#16]
Integration was working fine before performing an automatic update through HACS. After restarting home assistant it only shows an error message.

I also tried to re-install the integration but got the same result.

Settings page for this integration is no longer available.

## Version of home_assistant
core-2021.2.3
supervisor-2021.02.11 (stable channel)
Home Assistant OS 5.12 (production)

## Version of the custom_component
v1.2.1

## Describe the bug

Showing only an error message in dashboard instead of weather data:
"Diese Entität ist derzeit nicht verfügbar und ist verwitwet für eine entfernte, geänderte oder gestörte Integration oder ein Gerät."

## Debug log

```text


Logger: homeassistant.config_entries
Source: custom_components/dwd_weather/__init__.py:40
First occurred: 19:50:42 (1 occurrences)
Last logged: 19:50:42
Error setting up entry Villingen-Schwenning for dwd_weather

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/dwd_weather/__init__.py", line 40, in async_setup_entry
    time_window = entry.data[CONF_WEATHER_INTERVAL]
KeyError: 'weather_interval'



```

**Comment by FL550** [comment]
You don't have to reinstall the integration. Just delete the weather entity and the re-add it.

**Comment by andreas-2017** [comment]
Thanks for the quick response. This did the trick and I got it working again now.
