### ISSUE TITLE
Not loading on 2024.11

### ISSUE THREAD

**Issue by shennig84** [FL550/dwd_weather#162]
## Describe the bug
DWD weather not loading on 2024.11 beta 1
```
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 19:21:09 (1 Vorkommnisse)
Zuletzt protokolliert: 19:21:09

Setup failed for custom integration 'dwd_weather': Unable to import component: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 7, in <module>
    from homeassistant.core import Config, HomeAssistant
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 7, in <module>
    from homeassistant.core import Config, HomeAssistant
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

Logger: homeassistant.core
Quelle: core.py:549
Erstmals aufgetreten: 19:22:03 (1 Vorkommnisse)
Zuletzt protokolliert: 19:22:03

Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: fritz.device_tracker, sun.sensor, fritzbox.light, bluetooth, hassio.sensor, cast, zwave_js.select, scrape.sensor, notify, dreame_vacuum.sensor, homematicip_cloud.light, template, upnp.binary_sensor, meteoalarm.binary_sensor, zha.button, waste_collection_schedule.calendar, matter.binary_sensor, statistics, tts, fan, dlna_dmr.media_player, counter, shelly.button, google_assistant, dhcp, brother, fritzbox.switch, api, usb, esphome.switch, automation, zha.device_tracker, homematicip_cloud.lock, fritz.sensor, blueprint, frontend, shelly, recorder, hochwasserportal, zha.alarm_control_panel, mobile_app.notify, file_upload, fritzbox.button, hassio, zha.cover, onboarding, hardware, holiday, binary_sensor, zha.lock, battery_notes, switch, homematicip_cloud.alarm_control_panel, hacs, proximity.sensor, conversation, siren, kia_uvo, input_datetime, search, homematicip_cloud.climate, weather, shelly.number, update, esphome.binary_sensor, plant.number, plant, stt, fritz.button, dreame_vacuum.button, hacs.update, systemmonitor.sensor, fritz.update, text, matter.switch, battery_notes.button, sensor, kia_uvo.number, shelly.binary_sensor, homekit_controller, auth, tag, fritz.binary_sensor, media_player, energy.sensor, diagnostics, sun, dwd_pollenflug.sensor, zwave_js.sensor, shelly.event, waste_collection_schedule.sensor, matter.climate, xiaomi_ble, input_text, zha.select, script, number, battery_notes.sensor, xiaomi_ble.binary_sensor, device_tracker, ffmpeg, camera, logger, zha, co2signal.sensor, dreame_vacuum.select, homeassistant.scene, matter.vacuum, image_upload, image, my, mjpeg.camera, switch_as_x, xiaomi_ble.event, systemmonitor, intent, zwave_js.binary_sensor, input_boolean, network, time_date, select, xiaomi_miio.switch, fritz, timer, vacuum, xiaomi_miio.button, hassio.binary_sensor, xiaomi_miio.select, default_config, button, hochwasserportal.sensor, alarm_control_panel, homematicip_cloud.cover, shelly.climate, zha.fan, fritzbox.cover, zha.climate, esphome.update, dreame_vacuum, hassio.update, backup, open_meteo, template.sensor, http, filesize, homematicip_cloud.sensor, media_source, shelly.select, wake_word, system_log, persistent_notification, matter.light, cloud.binary_sensor, xiaomi_ble.sensor, application_credentials, valve, mobile_app.device_tracker, person, shelly.update, zha.sensor, min_max, dwd_weather_warnings.sensor, zha.switch, zone, zha.siren, zha.binary_sensor, androidtv_remote.media_player, time_date.sensor, adaptive_lighting.switch, nina.binary_sensor, zwave_js.event, energy, input_button, websocket_api, battery_notes.binary_sensor, dreame_vacuum.number, homekit_controller.binary_sensor, nina, cloud.stt, matter.lock, homekit_controller.switch, climate, waste_collection_schedule, kia_uvo.sensor, shelly.valve, config, device_automation, hacs.switch, scene, fritzbox.binary_sensor, homekit_controller.sensor, remote, system_health, dwd_weather_warnings, dreame_vacuum.switch, ibeacon, assist_pipeline, shelly.text, shelly.light, systemmonitor.binary_sensor, ssdp, matter.cover, homematicip_cloud.button, min_max.sensor, matter.sensor, kia_uvo.device_tracker, group.light, adaptive_lighting, ibeacon.device_tracker, fritzbox.sensor, upnp.sensor, schedule, zeroconf, homematicip_cloud, cloud, xiaomi_miio.number, zwave_js.number, dlna_dms, thread, zwave_js, xiaomi_miio.fan, input_select, statistics.sensor, fritz.image, homeassistant_alerts, zwave_js.switch, matter.fan, cover, homeassistant, lock, zha.number, androidtv_remote, mobile_app.sensor, event, repairs, epex_spot, xiaomi_miio, matter.button, zwave_js.button, calendar, plant.sensor, logbook, homeassistant_hardware, homekit_controller.button, shelly.switch, shelly.sensor, open_meteo.weather, filesize.sensor, homekit_controller.media_player, zha.update, moon.sensor, go2rtc, xiaomi_miio.binary_sensor, fritzbox.climate, wake_on_lan, homematicip_cloud.weather, fritzbox, webhook, analytics, mobile_app.binary_sensor, kia_uvo.lock, androidtv_remote.remote, matter.number, ibeacon.sensor, shelly.cover, fritz.switch, dreame_vacuum.vacuum, esphome.cover, homematicip_cloud.switch, input_number, time, scrape, zwave_js.update, dreame_vacuum.time, zha.light, matter, dlna_dmr, esphome, dreame_vacuum.camera, homematicip_cloud.binary_sensor, light, matter.update, holiday.calendar, group, stream, brother.sensor, upnp, matter.select, homeassistant_sky_connect, lovelace, cast.media_player, zwave_js.cover, trace, matter.valve, epex_spot.sensor, history, openplantbook, mobile_app, proximity, mjpeg, bluetooth_adapters, co2signal, switch_as_x.light, dwd_pollenflug, xiaomi_miio.sensor, moon, esphome.button, cloud.tts, matter.event, kia_uvo.binary_sensor The system is waiting for tasks: {<Task pending name='Task-4078' coro=<AbstractConfig.async_initialize.<locals>.sync_google() running at /usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py:114> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]>, <Task pending name='Task-4420' coro=<async_enable_report_state.<locals>.initial_report() running at /usr/src/homeassistant/homeassistant/components/google_assistant/report_state.py:187> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]>}

**Comment by shennig84** [comment]
Logger: homeassistant.core
Quelle: core.py:549
Erstmals aufgetreten: 19:22:03 (1 Vorkommnisse)
Zuletzt protokolliert: 19:22:03

Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: fritz.device_tracker, sun.sensor, fritzbox.light, bluetooth, hassio.sensor, cast, zwave_js.select, scrape.sensor, notify, dreame_vacuum.sensor, homematicip_cloud.light, template, upnp.binary_sensor, meteoalarm.binary_sensor, zha.button, waste_collection_schedule.calendar, matter.binary_sensor, statistics, tts, fan, dlna_dmr.media_player, counter, shelly.button, google_assistant, dhcp, brother, fritzbox.switch, api, usb, esphome.switch, automation, zha.device_tracker, homematicip_cloud.lock, fritz.sensor, blueprint, frontend, shelly, recorder, hochwasserportal, zha.alarm_control_panel, mobile_app.notify, file_upload, fritzbox.button, hassio, zha.cover, onboarding, hardware, holiday, binary_sensor, zha.lock, battery_notes, switch, homematicip_cloud.alarm_control_panel, hacs, proximity.sensor, conversation, siren, kia_uvo, input_datetime, search, homematicip_cloud.climate, weather, shelly.number, update, esphome.binary_sensor, plant.number, plant, stt, fritz.button, dreame_vacuum.button, hacs.update, systemmonitor.sensor, fritz.update, text, matter.switch, battery_notes.button, sensor, kia_uvo.number, shelly.binary_sensor, homekit_controller, auth, tag, fritz.binary_sensor, media_player, energy.sensor, diagnostics, sun, dwd_pollenflug.sensor, zwave_js.sensor, shelly.event, waste_collection_schedule.sensor, matter.climate, xiaomi_ble, input_text, zha.select, script, number, battery_notes.sensor, xiaomi_ble.binary_sensor, device_tracker, ffmpeg, camera, logger, zha, co2signal.sensor, dreame_vacuum.select, homeassistant.scene, matter.vacuum, image_upload, image, my, mjpeg.camera, switch_as_x, xiaomi_ble.event, systemmonitor, intent, zwave_js.binary_sensor, input_boolean, network, time_date, select, xiaomi_miio.switch, fritz, timer, vacuum, xiaomi_miio.button, hassio.binary_sensor, xiaomi_miio.select, default_config, button, hochwasserportal.sensor, alarm_control_panel, homematicip_cloud.cover, shelly.climate, zha.fan, fritzbox.cover, zha.climate, esphome.update, dreame_vacuum, hassio.update, backup, open_meteo, template.sensor, http, filesize, homematicip_cloud.sensor, media_source, shelly.select, wake_word, system_log, persistent_notification, matter.light, cloud.binary_sensor, xiaomi_ble.sensor, application_credentials, valve, mobile_app.device_tracker, person, shelly.update, zha.sensor, min_max, dwd_weather_warnings.sensor, zha.switch, zone, zha.siren, zha.binary_sensor, androidtv_remote.media_player, time_date.sensor, adaptive_lighting.switch, nina.binary_sensor, zwave_js.event, energy, input_button, websocket_api, battery_notes.binary_sensor, dreame_vacuum.number, homekit_controller.binary_sensor, nina, cloud.stt, matter.lock, homekit_controller.switch, climate, waste_collection_schedule, kia_uvo.sensor, shelly.valve, config, device_automation, hacs.switch, scene, fritzbox.binary_sensor, homekit_controller.sensor, remote, system_health, dwd_weather_warnings, dreame_vacuum.switch, ibeacon, assist_pipeline, shelly.text, shelly.light, systemmonitor.binary_sensor, ssdp, matter.cover, homematicip_cloud.button, min_max.sensor, matter.sensor, kia_uvo.device_tracker, group.light, adaptive_lighting, ibeacon.device_tracker, fritzbox.sensor, upnp.sensor, schedule, zeroconf, homematicip_cloud, cloud, xiaomi_miio.number, zwave_js.number, dlna_dms, thread, zwave_js, xiaomi_miio.fan, input_select, statistics.sensor, fritz.image, homeassistant_alerts, zwave_js.switch, matter.fan, cover, homeassistant, lock, zha.number, androidtv_remote, mobile_app.sensor, event, repairs, epex_spot, xiaomi_miio, matter.button, zwave_js.button, calendar, plant.sensor, logbook, homeassistant_hardware, homekit_controller.button, shelly.switch, shelly.sensor, open_meteo.weather, filesize.sensor, homekit_controller.media_player, zha.update, moon.sensor, go2rtc, xiaomi_miio.binary_sensor, fritzbox.climate, wake_on_lan, homematicip_cloud.weather, fritzbox, webhook, analytics, mobile_app.binary_sensor, kia_uvo.lock, androidtv_remote.remote, matter.number, ibeacon.sensor, shelly.cover, fritz.switch, dreame_vacuum.vacuum, esphome.cover, homematicip_cloud.switch, input_number, time, scrape, zwave_js.update, dreame_vacuum.time, zha.light, matter, dlna_dmr, esphome, dreame_vacuum.camera, homematicip_cloud.binary_sensor, light, matter.update, holiday.calendar, group, stream, brother.sensor, upnp, matter.select, homeassistant_sky_connect, lovelace, cast.media_player, zwave_js.cover, trace, matter.valve, epex_spot.sensor, history, openplantbook, mobile_app, proximity, mjpeg, bluetooth_adapters, co2signal, switch_as_x.light, dwd_pollenflug, xiaomi_miio.sensor, moon, esphome.button, cloud.tts, matter.event, kia_uvo.binary_sensor The system is waiting for tasks: {<Task pending name='Task-4078' coro=<AbstractConfig.async_initialize.<locals>.sync_google() running at /usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py:114> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]>, <Task pending name='Task-4420' coro=<async_enable_report_state.<locals>.initial_report() running at /usr/src/homeassistant/homeassistant/components/google_assistant/report_state.py:187> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]>}

**Comment by shennig84** [comment]
Possibly caused by this commit
https://github.com/home-assistant/core/pull/129163

**Comment by johnyb0y** [comment]
Can confirm.

![image](https://github.com/user-attachments/assets/11de2b95-d054-48b7-8e2f-e024624eda84)

After upgrading to **v2.1.20**:

![image](https://github.com/user-attachments/assets/fdd799cf-5e3f-40d5-a761-9d37d3e80b18)

`Logger: homeassistant.setup
Source: setup.py:334
First occurred: 10:30:35 (1 occurrences)
Last logged: 10:30:35

Setup failed for custom integration 'dwd_weather': Unable to import component: No module named 'homeassistant.core_config'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dwd_weather/__init__.py", line 8, in <module>
    from homeassistant.core_config import Config
ModuleNotFoundError: No module named 'homeassistant.core_config'`

Happy to provide additional information. Thank you.

**Comment by jpawlowski** [comment]
https://github.com/FL550/dwd_weather/releases/tag/v2.1.21

**Comment by FL550** [comment]
This is now implemented in the latest version.
