### ISSUE TITLE
v2.1.22 requires Home Assistant 2024.11.0b0

### ISSUE THREAD

**Issue by Qhilm** [FL550/dwd_weather#165]
## Version of home_assistant
2024.10.4

## Version of the custom_component
v2.1.20

## Describe the bug
When attempting to update to v2.1.22, the error "Failed to perform the action update/install. This version requires Home Assistant 2024.11.0b0 or newer." is displayed.

I assume this is not expected that a beta version of Home Assistant is made a requirement?

**Comment by Qhilm** [comment]
Maybe the issue is that v2.1.22 should also be a beta and not a normal release maybe – although I have no clue if that's possible in HACS.

**Comment by FL550** [comment]
This is intended behaviour, but you are right, this should rather be a pre-release. I changed this.

**Comment by Qhilm** [comment]
ok, that allowed me to go to v2.1.21 and solved my issue I had with v2.1.20. Thanks!
