### ISSUE TITLE
Required HA version is not available

### ISSUE THREAD

**Issue by olgru** [FL550/dwd_weather#166]
## Version of home_assistant
2024.10.4

## Version of the custom_component
2.1.20 -> 2.1.21

## Describe the bug
Install failed due to unmet requirements - but 2024.10.4 is the latest official version; the installation requirs 2024.11.0b0 -> which is a development version.

Maybe I've accidentially subscribed to a development channel - than this is my fault...

**Comment by dabepp** [comment]
Same here! No dev channel on my side. Seems to be a problem caused by this integration…

**Comment by dabepp** [comment]
Ok I went to HACS and reinstalled version 2.1.21 dwd is working again.
