### ISSUE TITLE
after upgrade from 1.2.28 i cant get todays forcast anymore

### ISSUE THREAD

**Issue by mannebk79** [FL550/dwd_weather#169]
Hi,
I used this template in an automation running on Verion 1.2.28 for my HA do decide if I want it to put out the awnings and run down the blinds and such: 
```
condition: template
value_template: >-
  {{state_attr('weather.dwd_weather_somewhere', 'forecast')[0]['temperature'] >=
  20.0 }}
alias: Confirm forecast for todays Outdoor Temperatur equals or exeeds 20.0°C
```
but now, after a long due update from ha 22.9, and therefore also pulling the hacs stuff up, that does not return a valid response any more. And after tinkering with it for a few days and reading closed issues, for the life of me, I cant figure out what im doing wrong, I see the forecast vales in lovelace cards, but in the dev tools I cant find em.

any input is apreciated, thank you kindly.

I feel I also would like to suggest, that @FL550 and @hg1337 from [https://github.com/hg1337/homeassistant-dwd] agree on some sort of a name and layout difference, and might also point out what makes their addon diffrent from each other in the readme? Cause, currently, they are not just named the same, they also look absoluty the same in the integrations main page, and how shoud a user therefore tell them apart, or know why chose one over the other, and you guys might want to somehow match your variables so code works with both of your addons, or you guys may join forces?

Cause Ive been going back and forth between your addons in the past days, but could not fix my issue with either of your addons.

Cheers Manny

**Comment by FL550** [comment]
Hi @mannebk79
the issue with your template is due to a change in HA some time ago, which removed the forecast from the weather entity attributes. You now have to do this via a actions call. Please see the README which explains this: https://github.com/FL550/dwd_weather/wiki#how-to-get-daily-maxmin-values

**Comment by mannebk79** [comment]
thank you kindly. I close the issue, will post my updated code later for others. i totally missed the eiki entry. sorry about that. cheers manne

Am 6. November 2024 08:20:33 UTC schrieb FL550 ***@***.***>:

**Comment by FL550** [comment]
@mannebk79 Regarding the difference between this integration and https://github.com/hg1337/homeassistant-dwd:

They were both created around the same time, not knowing we are working on the same topic until we both released the integration. As they have a different codebase a merge is not possible. Featurewise they basically do the same: providing you with dwd weather. However in detail they differ by the extra features they offer. Just use the one you are comfortable with.

**Comment by FL550** [comment]
>  i totally missed the eiki entry.

No worries! This indicates that I have to make it more prominent ;)
