### ISSUE TITLE
Config from dwd_weather is a deprecated alias / prepare for  HA Core 2025.11

### ISSUE THREAD

**Issue by jpawlowski** [FL550/dwd_weather#171]
Hello,

HA logs give a hint about a deprecation and retirement next year, which I wanted to pass on here as a reminder to adjust:

> Logger: homeassistant.core
> Quelle: helpers/deprecation.py:222
> Erstmals aufgetreten: 10:34:14 (1 Vorkommnisse)
> Zuletzt protokolliert: 10:34:14
>
> Config was used from dwd_weather, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'dwd_weather' custom integration

**Comment by FL550** [comment]
Thanks for reporting!
