### ISSUE TITLE
Too much padding in weather card using sections in HA

### ISSUE THREAD

**Issue by kersten-lohmeyer** [FL550/dwd_weather#172]
Is it possible to remove some padding for example or optimize graphics so that the "bezels" of the card don't look so big when using sections in HA?

Example using old layout:
<img width="433" alt="image" src="https://github.com/user-attachments/assets/d013df6a-4fab-4334-bebb-be3a497794c2">

Example using section layout:
<img width="513" alt="image" src="https://github.com/user-attachments/assets/f02c6361-50d8-42e5-835e-2107802d922e">

I'm not entirely sure if this component has anything to do with the graphics at all or is "just" gathering the data from DWD.

**Comment by FL550** [comment]
Hi, this integration only provides the data to the card. So if you want to change this, you can either do this by custom CSS or you ask at HA directly. 

Best regards

**Comment by kersten-lohmeyer** [comment]
Ok, thanks for clearing that up.
