### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by LuckyTriple7** [FL550/dwd_weather#19]
Logger: homeassistant.util.async_
Source: util/async_.py:129
First occurred: 10:58:44 (1 occurrences)
Last logged: 10:58:44

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for dwd_weather doing I/O at custom_components/dwd_weather/sensor.py, line 142: self._unique_id = f"{SENSOR_TYPES[self._type][0]}_{self._connector.dwd_weather.get_station_name(False).lower()}"

## Version of home_assistant
2021.3.4
-->

## Version of the custom_component
1.2.3
-->

**Comment by FL550** [comment]
Thank you very much for the report. This is now resolved in the new version [1.2.4](https://github.com/FL550/dwd_weather/tree/v1.2.4).
