### ISSUE TITLE
Return wind_bearing value as float

### ISSUE THREAD

**Issue by VDRainer** [FL550/dwd_weather#2]
## Version of the custom_component

1.0.0
## Describe the bug
Wondered why weather cards don't show the wind_direction.
For example [bram's weather-card](https://github.com/bramkragten/weather-card).
![Auswahl_381](https://user-images.githubusercontent.com/26381449/89783403-2766ca00-db17-11ea-9b27-ed8188de09b3.png)

Found out that the component doesn't return a float for the wind_bearing.
After changing https://github.com/FL550/dwd_weather/blob/88f696c12a45e7867a76ee4911a17f93848b35d0/custom_components/dwd_weather/weather.py#L90-L91 
to
```python
    @property
    def wind_bearing(self):
        """Return the wind direction."""
        return float(
            self._connector.weather_data.get_forecast_wind_direction(
                datetime.now(timezone.utc), False))
```
it works.
![Auswahl_382](https://user-images.githubusercontent.com/26381449/89783738-bb389600-db17-11ea-89fb-8ebf1893469e.png)

## Debug log

```text

Add your logs here.

```

**Comment by FL550** [comment]
I just released v1.0.1 3c88950 which fixes this. Thank you for your input!
