### ISSUE TITLE
Entities not available after update to 1.2.5

### ISSUE THREAD

**Issue by csoltenborn** [FL550/dwd_weather#20]
## Version of home_assistant
2021.3.4

## Version of the custom_component
1.2.5

## Describe the bug
Weather widget is not available any more after update:

![image](https://user-images.githubusercontent.com/352576/111430931-64bdb680-86fb-11eb-8f06-8f0947d79dc9.png)

This might maybe be related to some duplication going on:

![image](https://user-images.githubusercontent.com/352576/111431128-a9e1e880-86fb-11eb-919c-17a782a5ddbe.png)

## Debug log

No log entries...

**Comment by FL550** [comment]
Hm, strange. I see the same behaviour on my productive system. I don't know why the entity is re-added, but I cleaned the code a bit for v1.2.6. Maybe this resolves this. 

Nevertheless, if you remove the integration and re-add it, everything is working again.

**Comment by csoltenborn** [comment]
1.2.6 does not fix this - will then re-add the integration...

**Comment by FL550** [comment]
Hm, sorry for the inconvenience.

**Comment by csoltenborn** [comment]
Don't worry - thanks for the integration ;-) (and for giving me the opportunity to receive the GitHub price for "Fastest bug report ever" :-) )

**Comment by FL550** [comment]
3 minutes later, not bad :-D I was unaware it was that fast.

I'll leave this issue open for some time, as others will encounter this also.
