### ISSUE TITLE
`wind_speed_<location>` and `wind_gusts_<location>` sensors are quoted with inconsistent units

### ISSUE THREAD

**Issue by nikipore** [FL550/dwd_weather#24]
## Version of home_assistant
core-2021.3.4

## Version of the custom_component
v1.2.8

## Describe the bug
Both sensors declare a unit of m/s which is correct for all numeric values except for the scalar value (state) of  `wind_speed_<location>` which is quoted in km/h (3.6 times its current forecast value quoted in m/s).

**Comment by FL550** [comment]
Thanks, I'll fix this.

**Comment by FL550** [comment]
This is now corrected to km/h.
