### ISSUE TITLE
Integrate textual forecast (Produkt: Aktuelles Wetter und Vorhersagen)

### ISSUE THREAD

**Issue by hannemann** [FL550/dwd_weather#25]
Hi and thanks for your great integration :)

What do you think about integrating the DWD textual forecasts into your Plugin?  
* [Description](https://www.dwd.de/DE/wetter/warnungen_aktuell/objekt_einbindung/objekteinbindung_node.html#doc582840bodyText16)
* [Example (NDS)](https://www.dwd.de/DWD/wetter/wv_allg/deutschland/text/vhdl13_dwhg.html)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see a textual forecast of todays weather for my region aka 'Bundesland' in HA

**Describe alternatives you've considered**
* I tried to load the entire Page into an iframe card but that is not allowed
* than i tried to fetch the page into a template sensor entity but that failed because of the 255 characters constraint, Works but only truncated
* i considered creating a local webservice that fetches the HTML and transforms it into JSON so i could use a rest integration to load it into ha

**Additional context**
Would also be great to add pictures like warnings and current conditions but that is doable with a markdown card. So: nice to have :)

**Comment by FL550** [comment]
I will do this in the next days :)

**Comment by hannemann** [comment]
Great to hear :1st_place_medal:

**Comment by FL550** [comment]
I have added the forecasts to the underlying python module, but not yet to this integration. I am not sure on how to include the information for display in HA. Right now it will fetch the pure html code. But as far as I have seen, there is no possibility to display entity content as a webpage. 

If I strip all the HTML tags from the text, we are loosing the styling and we also have too much information to display this in a good way.

Do you have any ideas on how to display the weather forecast in HA?

**Comment by hannemann** [comment]
Would it be possible to strip out the contents of ```<div id="wettertext">``` and convert that to markdown?  
Than one could use the value in a markdown card.

I would also suggest to strip out all br Tags and style attributes...

**Comment by hannemann** [comment]
> Do you have any ideas on how to display the weather forecast in HA?

I would use a [browser_mod popup](https://github.com/thomasloven/hass-browser_mod#--popup) to display the data on demand.
Currently i use popup cards to display all the dwd images i am interested in and also created a css animation from current satellite images. Works quite well.

A card that can expand on click could be nice also... Accordion style or something like [lovelace-fold-entity-row](https://github.com/thomasloven/lovelace-fold-entity-row)

**Comment by FL550** [comment]
I've added this to the new version 1.2.9.

**Comment by hannemann** [comment]
It' s AWESOME!

Thank you very much!

**Comment by FL550** [comment]
You're welcome!
