### ISSUE TITLE
Integration broken since update to v1.2.9

### ISSUE THREAD

**Issue by Jpsy** [FL550/dwd_weather#26]
## Version of home_assistant

All latest:
core-2021.4.6 with Home Assistant OS 5.13 on RPi4b 8Gb

## Version of the custom_component

v1.2.9 (after upgrade from v1.2.8)

## Describe the bug
I had a fully functioning installation of v1.2.8  of the integration with many of the available entities activated.
After the upgrade all entities showed red exclamation marks in Configuration -> Integrations -> DWD....
The entities did not update their values anymore.

I then tried to uninstall and reinstall the custom integration (incl. restarts after each step).
Since then it is not possible to add the integration anymore. See the following screenshots and the debug log below.
I also waited for 12h and tried again to make sure this is not the result of a API issue on DWD side.

Before hitting "Send":
![image](https://user-images.githubusercontent.com/1806058/115964302-184c6e80-a524-11eb-986e-ebf66339cd3c.png)

After hitting "Send":
![image](https://user-images.githubusercontent.com/1806058/115964380-842ed700-a524-11eb-90d0-a304ce618a25.png)

The same happens when I try to use the geo coords (without station-id).

## Debug log

```
Logger: custom_components.dwd_weather.config_flow
Source: custom_components/dwd_weather/connector.py:61 
Integration: Deutscher Wetterdienst (documentation, issues) 
First occurred: 17:29:48 (1 occurrences) 
Last logged: 17:29:48

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/dwd_weather/config_flow.py", line 67, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/dwd_weather/config_flow.py", line 45, in validate_input
    await dwd_weather_data.async_update()
  File "/config/custom_components/dwd_weather/connector.py", line 54, in async_update
    return await self._hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 61, in _update
    self.dwd_weather.update()
  File "/usr/local/lib/python3.8/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 392, in update
    weather_report = download_weather_report(self.region_codes[self.region])
KeyError: 'Saarland'
```

**Comment by 19Fidel84** [comment]
I have the same Problem. I am running HassIo in a Vm on Synology


Logger: custom_components.dwd_weather.config_flow
Source: custom_components/dwd_weather/connector.py:61
Integration: Deutscher Wetterdienst (documentation, issues)
First occurred: 18:00:41 (5 occurrences)
Last logged: 18:06:21

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/dwd_weather/config_flow.py", line 67, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/dwd_weather/config_flow.py", line 45, in validate_input
    await dwd_weather_data.async_update()
  File "/config/custom_components/dwd_weather/connector.py", line 54, in async_update
    return await self._hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 61, in _update
    self.dwd_weather.update()
  File "/usr/local/lib/python3.8/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 392, in update
    weather_report = download_weather_report(self.region_codes[self.region])
KeyError: 'Saarland'

**Comment by FL550** [comment]
Ich sag jetzt mal lieber nicht, dass ich das Saarland vergessen habe 😄

I missed this in the underlying integration, but this is now fixed in version v1.2.10. Sorry for the inconvenience.

**Comment by 19Fidel84** [comment]
um Gotteswillen das wichtigste Bundesland :P

**Comment by Jpsy** [comment]
> Ich sag jetzt mal lieber nicht, dass ich das Saarland vergessen habe 😄

Ohleck, das so hädschde awweile bis dahin derfe. Awweile bische unnedursch. :D

Thanks for the ultra quick fix!

**Comment by 19Fidel84** [comment]
Top danke nach Update findet und läuft

**Comment by FL550** [comment]
> > Ich sag jetzt mal lieber nicht, dass ich das Saarland vergessen habe 😄
> 
> Ohleck, das do hädschde awweile nid sahn derfe. Awweile bischde unnedursch. :D
> 
> Thanks for the ultra quick fix!

Da muss ich mich aber echt anstrengen das zu verstehen 😅

You're welcome!
