### ISSUE TITLE
Hourly Weather States

### ISSUE THREAD

**Issue by FaserF** [FL550/dwd_weather#29]
**Is your feature request related to a problem? Please describe.**
Just a feature request :) 

**Describe the solution you'd like**
I would love to see hourly weather states (and temperatures) for the current day. Meteograms for example offers something like that in combination with DWD. 
It would be awesome to see something similar, that you are currently doing with the days, just also with the hours of the current day.

**Describe alternatives you've considered**
Using another integration with another weather provider. But I would prefer to just use DWD

**Additional context**
I would just say to thank you very very much for your great addon.

**Comment by FL550** [comment]
Thanks for the feedback!

You can do this already either by setting the interval during the configuration to 1 hour or by enabling the sensors and using a weather template.

Hope this helps.

**Comment by FaserF** [comment]
WOW! You are just awesome. It was so simple and also everything was written in your docs. So shame on me. 
I was using your addon since such a long time, that I never thought that this was already implemented.

**Comment by FL550** [comment]
You're welcome :)
