### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by seanomat** [FL550/dwd_weather#3]
**Is your feature request related to a problem? Please describe.**
As far as I can see, the dwd also supplies values for current percipitation and current Cloud-Cover.

Would be great if your component would supply these as well.

Also more a question: how often is the current info updated?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FL550** [comment]
Hey, precipitation and cloud-cover is included in the last release v1.1.0! 

The current infos aren't direct measurements, as these aren't available as far as I can see.  The only option to get hourly updated values is by downloading a 650MB file which is not practicable.

The "current" values are therefore only the current hourly forecast data, which are updated by the DWD every 6 hours.

**Comment by seanomat** [comment]
I was hoping I could avoid a local weather station.
Current precipitation and cloud-cover are quite important to my setup and need to be current and  accurate.
Right now I use brightsky.dev which also sources the DWD information. It seems to be more current, but is also only updated every hour. All other services I checked are very current but not very accurate.
I guess I won't get around my own weather station :(

**Comment by FL550** [comment]
If the accurcy of values are important for you, I guess this is the only option. Unfortunately, forecasts can never be so accurate that you can substitute a real sensor. But a weather station is a cool project. I am also planning to build my own.
