### ISSUE TITLE
Bright Sky - current weather

### ISSUE THREAD

**Issue by bulburDE** [FL550/dwd_weather#31]
I've independently encountered this integration and an [attempt to add bright sky as an integration](https://github.com/mweinelt/hass-brightsky-client). So I've wondered if you have any plans of using the [bright sky API](https://brightsky.dev/). I was just surprised that I couldn't find any reference to it here.
I really like the concept of the OpenData program and am just looking for the best way to use it in my home automation system.

Additionally, in the readme is the following note: 
> Please note, that the "current" weather values are not measured values. The values shown are the forecasted values for the actual hour. The forecast itself is updated every 6 hours. If anyone knows a source for actual measurements, please let me know.

As far as I understand the Bright Sky documentation, it's possible to get current data from the dwd, right?

> Data Origin
> Data with the observation types current and historical is published by DWD's extensive network of observation stations. The difference between these two types lies only in the level of quality assurance that the DWD has provided (see the DWD's Climate Data Center README). Data with observation type forecast comes from MOSMIX.

**Comment by FL550** [comment]
Very interesting and thanks for the comment. I will have a look at this in the next days!

**Comment by timmkrause** [comment]
DWD itself also offers historical data, see „3.1 Wo findet man Mess- und Beobachtungsdaten vom aktuellen Tag?“:

https://www.dwd.de/DE/leistungen/opendata/faqs_opendata.html

**Comment by FL550** [comment]
I had a closer look into this. The actual measurements come from the very limited [list of POIs](https://opendata.dwd.de/weather/weather_reports/poi/). So for most areas the measured values are far away from the actual position. An even if you are close to a POI, the measured values are 1-2 hours late.
