### ISSUE TITLE
Sensors only show "ok"

### ISSUE THREAD

**Issue by p-rintz** [FL550/dwd_weather#4]
## Version of the custom_component
1.1.0

## Describe the bug
The new sensors will all only show "ok" as data on my overview.
Data seems to be available, but only with the timestamp as key, see the below screenshot.
Is it possible to simply retrieve the daily precipitation % value for today?

![image](https://user-images.githubusercontent.com/13933258/90318445-ce40d100-df30-11ea-94bb-d56af54c1918.png)

**Comment by FL550** [comment]
Hey, this is not what the sensors are for. The sensors should provide especially the data for every hour, in case someone need this.

The daily precipitation however is already included in the normal weather entity. If you need the specific value as a sensor, have a look at HAs template sensors. With a template sensor you can extract exactly the data you need as a single sensor. Hope this helps!

**Comment by p-rintz** [comment]
Hi, thanks for the quick reply.

I gathered that it probably was something like that.

Though I cannot see the precipitation in the normal weather entity, is there anything I need to configure for it to show?
Using "precipitation" or "precipitation_probability" as secondary values in the entity do not show any values.

![image](https://user-images.githubusercontent.com/13933258/90319111-840e1e80-df35-11ea-8054-c51f2025bb57.png)

**Comment by FL550** [comment]
The weather entity has more data available, you can see this at the developer settings.

Viele Grüße nach Mühlheim ;-)

**Comment by p-rintz** [comment]
Ah, yeah. I can see how it is now. Thanks for the help.

I'll have to look into how the templates work for now. I always put off looking into them as I didn't really need them yet.

Grüße zurück. 😄

**Comment by skipper22hassio** [comment]
Struggeling with the same thing. 
I get the weather attributes to work as sensors
`sensor:
  - platform: template
    sensors:
      dwd_temperature:
        friendly_name: "DWD Temperature"
        entity_id: weather.dwd_weather_frankfurt_m
        unit_of_measurement: '°C'
        device_class: temperature
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m', 'temperature') | d   ##}}"`

but I don't know how to process the data within an enabled sensor. Any hints? 

Grüße aus dem Nordend

**Comment by FL550** [comment]
Na klar 😄:
```
{{ state_attr('sensor.temperature_bad_homburg', 'data')[0]}}              // {'datetime': '2020-08-19T16:00:00.000Z', 'value': 26.3}
{{ state_attr('sensor.temperature_bad_homburg', 'data')[1]}}              // {'datetime': '2020-08-19T17:00:00.000Z', 'value': 25.3}
{{ state_attr('sensor.temperature_bad_homburg', 'data')[0]['value']}}     // 25.3
```

**Comment by herrwusel** [comment]
First of all thanks for the DWD implementation. I'm trying to create a illuminance sensor based on the cloud_coverage. How are the data attributes updated? For calculation I would like to take the value for the current hour of course (later on interpolated data maybe). It looks like the sensor keeps some values from the past but when does it "move forward"?

**Comment by FL550** [comment]
The data is updated every 6 hours. The data displayed is not an actual measurement, as I haven't found a source for this.
