### ISSUE TITLE
installation issue / question

### ISSUE THREAD

**Issue by michapr** [FL550/dwd_weather#41]
## Version of home_assistant
Home Assistant 2021.12.10

## Version of the custom_component
1.2.17 (latest)

## Describe the bug
Installed via HACS - then restarted HA. 
No integration visible - cannot add a card and cannot make the described setup anywhere - maybe I do something wrong?

## Debug log
no more in log (debug log was enabled in config as described )

```text
2022-01-28 17:09:41 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dwd_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

Thanks!

**Comment by FL550** [comment]
Hi michapr, the log shows that the component has been loaded. Nevertheless it is not showing in the Add integration screen, correct?

**Comment by michapr** [comment]
Oh.... sorry... I was at wrong place. Haven't seen the "add integration" in configuration. I was at "add card".

At "add integration" is it inside... and can be configured. Thanks!
