### ISSUE TITLE
Add wind_speed, wind_gust and wind_direction to forecast

### ISSUE THREAD

**Issue by michapr** [FL550/dwd_weather#44]
**Is your feature request related to a problem? Please describe.**
would be nice to get these values in forecast to display it (daily and hourly)

**Describe the solution you'd like**
add the parameters in script (they are available, but not used for forecast)

**Describe alternatives you've considered**
-

**Additional context**
Of course would be great to offer additional the direction symbols instead of numeric direction degree value ;)

**Comment by FL550** [comment]
Hi, thanks for your request and my late reply. I've been quite busy the last days.

Of course I can include the values in the forecast. Last time I checked the developer pages, wind should not be included in the forecast, but now it is: https://developers.home-assistant.io/docs/core/entity/weather/?_highlight=forecast#forecast

Daily **AND** hourly forecast values are not possible unfortunately, as there is no distinction criteria if a value is related to a day or an hour. 

I'll update the code for the forecast and publish a new release this weekend.

**Comment by michapr** [comment]
Hi, thank you for your response!
As I can see only the wind_speed and wind_bearing included here, but not wind_gust - the most important parameter for the forecast,...
Isn't it possible to add additional "custom" parameters to these listed parameters? So that an "advanced" user could use it in custom cards?
And - why it is not possible to add it in daily AND hourly forecasts - not clear for me just now ;) Where is the difference to temperature, condition, pressure etc.? Of course it is interesting to know how it will be tomorrow (even if have not hourly forecast for next day) - or when it will be today critical - in the morning, afternoon or night... - so hourly and daily would be nice to have :)

THANKS!

**Comment by FL550** [comment]
It just released a new version, which includes the values you requested.

**Comment by michapr** [comment]
Hi GREAT !!!

Thank you! Nice work - and fast!

**Comment by marcoaureliovaz** [comment]
Hello!

Thank you so much for the update and integration!

I would like to automate my shutters based on wind direction and speed/gust.
But the Entities bring no value/state, it's nevertheless possible to see a historical when I see YAML.
I would expect something like precipitation value (value is readiable)

See the screenshots
![Screenshot_20240203-093701](https://github.com/FL550/dwd_weather/assets/155663270/9c277823-cd72-4339-8215-668e80154660)
![Screenshot_20240203-093621](https://github.com/FL550/dwd_weather/assets/155663270/6bd7f076-6ef4-46ae-ad5a-5c3927d7afc4)
![Screenshot_20240203-093729](https://github.com/FL550/dwd_weather/assets/155663270/773a4ad4-fac3-45e8-8faf-3c7427b3317c)

**Comment by marcoaureliovaz** [comment]
Is it possible to check it?
Thank you so much!

**Comment by FL550** [comment]
I'm not quite sure if I get this right. Do you mean the "Unknown" state of the sensor?

**Comment by marcoaureliovaz** [comment]
Hello!
Yes

**Comment by FL550** [comment]
Btw.: Can you please open a new issue for this?

**Comment by FL550** [comment]
Ok, I'll have a look.

**Comment by FL550** [comment]
I can't reproduce this on my side. So can you please open a new issue and post the relevant debug logs in it? This is the only way I can troubleshoot this.
