### ISSUE TITLE
Forecasted data as triggers

### ISSUE THREAD

**Issue by sk365** [FL550/dwd_weather#46]
Hi, 
thank you for programming this excellent integration. 
Please allow me a newbie question: 
How do I use forecasts delivered by the sensor as triggers?
For example, I want my window blinds to open if the maximum of forecasted wind speeds within the next n hours exceed a certain threshold. So, how would I access the wind speed in n hours from now?
Thank you for your help. 
Stefan

**Comment by diplix** [comment]
you’ll have to use a template sensor , i did that to create an alarm if the temperature drops below 0°C.

```
  - sensor:
      - name: Tiefsttemperatur in 24 h
        unique_id: E74013A7-348C-44F8-B4B1-93E5992C1840
        unit_of_measurement: °C
        state: >-
            {% set tomorrow = (as_timestamp(now() + timedelta(hours=24)) | timestamp_local) %}
            {% set today = state_attr('sensor.temperature_berlin_tegel', 'data')| selectattr('datetime', 'lt', tomorrow) | map(attribute='value') | list %}
            {{ today | min }}
```
this should also work to get a sensor to show the highest wind speed in the next n hours which can then be used as an automation trigger.

**Comment by diplix** [comment]
sorry, i did an incomplete copy&paste missing the `template:` line. i corrected the code above and hope it works like this.

**Comment by sk365** [comment]
Hi Felix, 

thank you again. 
It works now, also with wind and other parameters. 
But strangely it works only timedelta is set to 12 hours or more. 
If timedelta is set to a lesser amount, the template sensor yield either 0 or „not available“
I did set the DWD weather integration to 1 hour sampling interval. 
Any idea what to do?

Best, 
Stefan

**Comment by diplix** [comment]
seems to work for me, at least with the temperature.
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/4541494/158653171-cc7b969e-4aaa-43c7-bd05-4bccae0dc846.png">

**Comment by sk365** [comment]
now working for me, too 
no idea why it didn’t before
thanks again

**Comment by FL550** [comment]
Is the sensor showing the forecast data in the correct interval?

**Comment by sk365** [comment]
Yes it is

**Comment by FL550** [comment]
oh, I oversaw your last comment 😅 
glad everything is working now!
