### ISSUE TITLE
Integration does not show up in HA after adding to HACS

### ISSUE THREAD

**Issue by hobbes444** [FL550/dwd_weather#49]
I have added the integration to HACS, but it still does not show up in HA when I search for it. I probably did something trivially wrong, I just can't put my finger on it.

**Comment by FL550** [comment]
Hi, do you have the same issue like this one: [https://github.com/FL550/dwd_weather/issues/41](#41)?

**Comment by hobbes444** [comment]
Hmm, this is weird, yesterday evening it did not show up in this list, I am certain of it:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/3350433/164159248-ff40d273-d560-4a3e-b1f8-775ba68655a4.png">

Now it shows up this morning, without me even doing any additional restart or changing anything in HA.

I am really positive that I was clicking on the "add integration" button, unlike in #41 .

Anyway, this can be closed and sorry for wasting your time, I should have waited a day first.
