### ISSUE TITLE
Wind speed displayed in km/h instead of m/s

### ISSUE THREAD

**Issue by skipper22hassio** [FL550/dwd_weather#5]
Wind Speed is displayed in the Weather Forecast Card "detail view" (click on card) in km/h instead of m/s

Lovelace Card code: 
entity: weather.dwd_weather_frankfurt_m
type: weather-forecast

![image](https://user-images.githubusercontent.com/52670824/90645879-c8036b00-e236-11ea-86b2-3a5c51a2579e.png)

Result
![image](https://user-images.githubusercontent.com/52670824/90645150-e87ef580-e235-11ea-9637-2262eb6e84ac.png)

DWD Integration: v1.1.2

**Comment by FL550** [comment]
Thanks, I missed this one! I will fix it later this day.

**Comment by FL550** [comment]
This is fixed in v1.1.3.

Thanks again for the heads-up!
