### ISSUE TITLE
Windspeed km/h m/s Problem 

### ISSUE THREAD

**Issue by sblogoshs** [FL550/dwd_weather#51]
Hallo.

Ein Bild sagt mehr als…..
Die Maßeinheiten bei der Windgeschwindigkeit sind unterschiedlich und bei der Windrichtung gibts ein Problem bei der Übersetzung von Ost (ONO / E-NO).

Hello.

A picture says more than...

The units of measurement in the wind speed are different and there is a problem with the transmission of east (ONO / E-NO) in the wind direction.

![0DB1A37D-2E19-4CFD-9901-D2E1F46C9802](https://user-images.githubusercontent.com/26520301/164387775-a9fadca8-3296-4db2-99be-431e35f882ae.jpeg)
![E5FB571A-1E4F-41E8-8C6F-B852CEDD357D](https://user-images.githubusercontent.com/26520301/164387779-d9735cee-4ea9-40f5-9be9-c585d3de8fee.jpeg)

**Comment by FL550** [comment]
Hey, during the last change I obviously forgot to adjust the unit. But the value is km/h which is correct.

The display value on the second image is nothing I can change.

**Comment by FL550** [comment]
Ok, I've double checked the code. None of these issues are related to the integration. The error must lie within the weather card you are using.

**Comment by sblogoshs** [comment]
Okay.

Thank you very much!
