### ISSUE TITLE
Integration in Home Assistant does not work

### ISSUE THREAD

**Issue by Johnyboy1984** [FL550/dwd_weather#53]
![image](https://user-images.githubusercontent.com/96473114/167460385-f43f2412-2315-4614-ba7a-035d1c4e1bde.png)

![image](https://user-images.githubusercontent.com/96473114/167460552-059f516c-9eea-44dc-bb58-85f84197d60f.png)

![image](https://user-images.githubusercontent.com/96473114/167460606-3078c4b4-2b3e-4a8f-9154-6871b79d3c66.png)

![image](https://user-images.githubusercontent.com/96473114/167460868-32eabc22-e071-4f8d-adbd-58feb600e223.png)

![image](https://user-images.githubusercontent.com/96473114/167460953-918746cf-6809-4157-b40f-f1ba2c1d2841.png)

**Comment by BassT1** [comment]
Same here: 
![image](https://user-images.githubusercontent.com/95672670/167463969-1e8415c5-1f08-41a4-8fad-5f4dee8daa44.png)
![image](https://user-images.githubusercontent.com/95672670/167464190-97c1f006-0fd1-4e4a-b8f3-009881f03d3f.png)

**Comment by FL550** [comment]
Hi, I think this is related to the SSL error which was an issue today. The SSL certificate is renewed, but homeassistant is still getting an invalid answer from the servers. 

If I test the package which throws the error independent, no problems occur at all. So I guess HA is doing some SSL caching and I don't know how this can be resolved. Maybe we just need to wait a bit.

**Comment by VDRainer** [comment]
Downgrade to 1.2.17 works for me after 1.2.20 install.
I'm pretty sure i had 1.2.19 before?
@FL550  ?

**Comment by FL550** [comment]
@VDRainer Yep, I messed things up with the release numbering. 1.2.19 was the last one.

**Comment by FL550** [comment]
I just released a beta version which fixes the error for me. Can someone please verify it's working for you as well?

**Comment by FranknStone** [comment]
Your beta solved the problem for me! Thanks!

**Comment by perabo65** [comment]
Solved for me too, thanks!

**Comment by FL550** [comment]
I'm glad to hear that. 

Fun fact: I changed nothing compared to the previous version except the new version numbers 😂 Which proves, that this was a caching issue.

**Comment by homeassistanthomegear** [comment]
Problem fixed by beta. Thx for your quick response!

**Comment by homeassistanthomegear** [comment]
That's IT 🙂

**Comment by Ozeanesel** [comment]
Thanks

**Comment by BassT1** [comment]
Works, thanks!

**Comment by larsschwegmann** [comment]
Could you release this as a normal release if it's working correctly? I don't want to switch to the beta channel

**Comment by Tobiti** [comment]
The beta fixed it for me too

**Comment by WLammert** [comment]
is there a description on how to get the beta version? I'm on Home Assistant Supervised and found no way to get the beta version of the plugin

**Comment by larsschwegmann** [comment]
You'd have to click "Redownload" on the integration in HACS, and then activate the "Show Beta Versions" checkbox. This will put oyu on the beta release channel f the integration though.

**Comment by FL550** [comment]
I just released the standard version. I waited to see, if this really fixes the issue.

**Comment by Johnyboy1984** [comment]
Hab auf die Standartversion .21 geupdatet und es läuft. Hatte vorher die Beta. Läuft beides. Vielen Dank.

**Comment by hans-sein** [comment]
Habe das gleiche Problem, auch mit der aktuellen Version. 
same Problem, using the actual version.

**Comment by hans-sein** [comment]
Habe jetzt auch das Problem - unbekannter Fehler -
 Version ist aktuell. 
Problem - unnown error - using the actual version. 

![30D2DD53-AD65-4142-895F-AE37B931167B](https://user-images.githubusercontent.com/76510557/193466691-0ac6f087-5f45-44d2-9e56-f22a92baa429.jpeg)

**Comment by FL550** [comment]
Das scheint ein anderes Problem zu sein. Welche Stations-ID wolltest du verwenden?

**Comment by FL550** [comment]
Das liegt leider daran, dass der DWD für diese Station keine Daten zur Verfügung stellt: https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/K2226/kml/

**Comment by hans-sein** [comment]
Danke für die Hilfe! Hab eine andere Station in der Nähe genommen und das funktioniert prima.
