### ISSUE TITLE
Statistics Unterstützung

### ISSUE THREAD

**Issue by vonwange** [FL550/dwd_weather#55]
Hallo!
Erstmal danke für die Erweiterung!

Wäre es möglich auch Statistiken zu unterstützen? 

Danke
M

**Comment by FL550** [comment]
Was für Statistiken wären das denn zum Beispiel?

**Comment by FL550** [comment]
Statistics lassen sich nur für Sensoren nutzen, nicht für die Weather Entity. Für die Sensoren werde ich das integrieren.

**Comment by vonwange** [comment]
DANKE! Gerade brav das Update gemacht! @FL550

**Comment by FL550** [comment]
Gerne 😉
