### ISSUE TITLE
deprecated methods on an instance of WeatherEntity

### ISSUE THREAD

**Issue by swa72** [FL550/dwd_weather#59]
## Version of home_assistant
2022.6 -> 2022.7

## Version of the custom_component
1.2.22

## Describe the bug

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308 
Integration: Weather (documentation, issues) 
First occurred: 06:46:24 (1 occurrences) 
Last logged: 06:46:24

custom_components.dwd_weather.weather::DWDWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.
```

**Comment by swa72** [comment]
Duh. ;-)

**Comment by FL550** [comment]
Aber danke für das melden. Ich werde mich demnächst darum kümmern 😉
