### ISSUE TITLE
Can't add the integration 

### ISSUE THREAD

**Issue by HyperCriSiS** [FL550/dwd_weather#62]
## Version of home_assistant
2023.1.7

## Version of the custom_component
1.2.24

## Describe the bug
Hi, 

I want to add the integration and I get the error:
Der Konfigurationsfluss konnte nicht geladen werden: 500 internal Server Error Server got itself in trouble. 

Thanks
Hyper 

## Debug log

Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 15:06:51 (3 occurrences)
Last logged: 15:07:05

Unable to install package simple_dwd_weatherforecast==1.1.5: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [3 lines of output] Building lxml version 4.9.2. Building without Cython. Error: Please make sure the libxml2 and libxslt development packages are installed. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details. [notice] A new release of pip available: 22.3.1 -> 23.0 [notice] To update, run: pip install --upgrade pip

**Comment by FL550** [comment]
Hi, 

I did a bit of research and it seems like your platform is missing the required libraries as described here: https://github.com/lxml/lxml/blob/master/INSTALL.txt

Can you please install them and see if the error persists?

**Comment by HyperCriSiS** [comment]
I am using HA on Dietpi which tells me to install Python modules like this:

```
Home Assistant is installed within a dedicated Python environment, powered by: [pyenv/pyenv](https://github.com/pyenv/pyenv).
This places a standalone Python instance which runs completely independent from any other installed Python instance or modules. If you need to install additional Python modules into this pyenv environment, update Python itself or similar, you need to open a shell as user homeassistant and activate the pyenv environment:

sudo -u homeassistant bash
. /home/homeassistant/pyenv-activate.sh
pip3 install <module> # Or whichever install/update you need to do
```
When I try this I get: 
ERROR: Could not find a version that satisfies the requirement py27-lxml (from versions: none)
ERROR: No matching distribution found for py27-lxml

ERROR: Could not find a version that satisfies the requirement python3-lxml (from versions: none)
ERROR: No matching distribution found for python3-lxml

When I try it to install it like it is described in the install.txt, it asks for a HA password and it strangely does not accept mine :sweat_smile:

Any idea what I am doing wrong? :smile:

**Comment by FL550** [comment]
You're welcome! I'm happy to help ☺️
