### ISSUE TITLE
Integration went missing from HACS

### ISSUE THREAD

**Issue by m4dm4xi** [FL550/dwd_weather#63]
From one day to another this integration went missing from HACS.
My dashboard suddenly said "Integration not available".

HACS looks like this:
![Screenshot_2023-03-21-08-54-14-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/42769944/226546678-a3e01797-8729-4463-8332-a4494b0b4f58.jpg)

What happened?

**Comment by FL550** [comment]
The integration is still available. It was a fault in the info file and is now fixed with the latest release v1.2.25.
