### ISSUE TITLE
Irradiance state still wrong

### ISSUE THREAD

**Issue by CanisLupus-42** [FL550/dwd_weather#66]
After the last release the irradiation data in the attributes are fixed, but the actual state of the entity still is off by the factor of 3,6. 

Regards
CanisLupus

![grafik](https://github.com/FL550/dwd_weather/assets/88034398/fe4a7e17-4098-40bd-a47c-b8e3b77eddc0)

**Comment by FL550** [comment]
Thanks again for pointing this out. I missed the second occurence of this in the code. Maybe I should do some refactoring...
