### ISSUE TITLE
The Deutscher Wetterdienst (DWD) Weather Warnings YAML configuration is being removed

### ISSUE THREAD

**Issue by ulf78** [FL550/dwd_weather#67]
## Version of home_assistant
Home Assistant 2023.6.1

## Version of the custom_component

v1.2.27

## Describe the bug

After latests HA update I got the following warning:

> The Deutscher Wetterdienst (DWD) Weather Warnings YAML configuration is being removed
> This stops working in version 2023.8.0. Please address before upgrading.
> Configuring Deutscher Wetterdienst (DWD) Weather Warnings using YAML is being removed.
> 
> Your existing YAML configuration has been imported into the UI automatically.
> 
> Remove the Deutscher Wetterdienst (DWD) Weather Warnings YAML configuration from your configuration.yaml file and restart Home Assistant to fix this issue.

**Comment by FL550** [comment]
Hi, thanks for your comment, but this is related to the DWD Weather warnings integration and not with this integration. Nevertheless, you should be able to get rid of this error according to the error messeage by removing the configuration from your configuration.yaml

Best regards
