### ISSUE TITLE
Aktualisierungsintervall Einstellung

### ISSUE THREAD

**Issue by DeckardCain2014** [FL550/dwd_weather#68]
Hallo zusammen,

gibt es eine Möglichkeit, das Aktualisierungsintervall einzustellen? Ich nutze die Integration als Lüftungsempfehlung. Wenn aber der Wert bis zu 1h alt ist, funktioniert das so nicht mehr ganz ;)

**Comment by FL550** [comment]
Hi,

leider nicht, da die Sensorwerte nicht in einer höheren Frequenz vom Deutschen Wetterdienst zur Verfügung gestellt werden. Für den Anwendungsfall würde ich auch eher auf eigene Sensoren setzen.

**Comment by FL550** [comment]
Eventuell funktionieren die Werte in [v2.0.0](https://github.com/FL550/dwd_weather/releases/tag/v2.0.0) besser für den Anwendungsfall.
