### ISSUE TITLE
Koordinaten von Messstationen falsch

### ISSUE THREAD

**Issue by LeonRein** [FL550/dwd_weather#71]
Es scheint so, als ob in [stations.py](https://github.com/FL550/simple_dwd_weatherforecast/blob/master/simple_dwd_weatherforecast/stations.py) einige Koordinaten falsch sind. Diese scheinen ca. 50 km zu weit südlich zu sein. Scheint bei mehreren der Fall zu sein. Ich konnte jedoch noch kein Muster feststellen.

Beispiel Zeile [1328](https://github.com/FL550/simple_dwd_weatherforecast/blob/ee9e58173d1bd30ac8606d7a63ada9b6267b8601/simple_dwd_weatherforecast/stations.py#L1328):
H883  ---- SIEGEN (KLÄRANLAGE)   50.51    8.00   263 Nordrhein-Westfalen

Siegen liegt allerdings bei 50.88, 8.02.

**Comment by FL550** [comment]
Die Daten kommen direkt vom DWD, von daher habe ich da leider keinen Einfluss drauf. Ich schaue die Tage aber mal nach einer Aktualisierung.

**Comment by LeonRein** [comment]
War mein Fehler. Habe die Koordinaten als Dezimalgrad interpretiert. Es sind aber Grad.Minute.
