### ISSUE TITLE
Regenmenge in Kg pro Quadratmillimeter?

### ISSUE THREAD

**Issue by Maschinenherz** [FL550/dwd_weather#72]
![image](https://github.com/FL550/dwd_weather/assets/114295630/a99ca543-0198-4aeb-8b42-348e5c3bdab0)

Ich glaube nicht, das es beabsichtigt ist ;)

**Comment by FL550** [comment]
Tatsächlich ist das die richtige Einheit die auch der DWD ausliefert. Aber da 1 Liter Wasser einem Kilogramm entspricht, ist die Einheit äquivalent zu l/m². Und 1 l Wasser auf einem m² wiederum entspricht 1mm Regenhöhe pro m². 

Ich vermute mal, geläufiger ist die Angabe in mm Regen pro m², oder?

**Comment by Maschinenherz** [comment]
Ich habe schon  l/m² gehört, aber meistens nur, wenns um sehr starke Regenfälle ging.  Normalerweise ist es mm/m²
