### ISSUE TITLE
Verlinkung in der Hilfe zu den station_ids fehlerhaft

### ISSUE THREAD

**Issue by robo-kob** [FL550/dwd_weather#73]
## Version of home_assistant
die aktuellste

## Describe the bug
Verlinkung in der Hilfe zu den station_ids fehlerhaft

## Debug log

```text

Add your logs here.

```

**Comment by robo-kob** [comment]
I think this is the correct information?
https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/mosmix_stationskatalog.cfg;jsessionid=491F2BA487383F46185EB694E65FE5B5.live31094?view=nasPublication&nn=16102

Regards Roli

**Comment by FL550** [comment]
Yeah, this is my bad. Sorry for this. I will publish an update of the integration in a few weeks, which makes them obsolete. And in preparation for this I updated the files with the station_ids. So your link is the correct one and I will leave this issue open for reference.

Best regards

**Comment by FL550** [comment]
Obsolete with [v2.0.0](https://github.com/FL550/dwd_weather/releases/tag/v2.0.0).
