### ISSUE TITLE
Pre-Bug: Need to Update for 2024.3

### ISSUE THREAD

**Issue by MickLesk** [FL550/dwd_weather#74]
## Version of home_assistant
Home Assistant 2023.9.0b0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230830.0 - latest
## Version of the custom_component
Newest Version

## Describe the bug
See it as a pre-planning / bug in the future. The system must be updated to the new variables so that HA can work with it in the 2024 version.

It is only a hint / warning. 

"The dwd_weather integration uses outdated forecasts.
This no longer works in version 2024.3.0, please fix this before upgrading.
The dwd_weather integration uses the deprecated forecast attribute.

Please report it to the custom integration author." 

<img width="406" alt="image" src="https://github.com/FL550/dwd_weather/assets/47820557/182f3bcc-d6bc-4ee7-b112-96b1a8ef7dd8">

## Debug log

```text

Add your logs here.

```

**Comment by FL550** [comment]
Hi, thank you very much for the info!

**Comment by fwmarcel** [comment]
Here is the link to the technical documentation: https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
I have the same message - is it something in my configuration or is it an issue in the code?

**Comment by FL550** [comment]
Fixed in [v2.0.0](https://github.com/FL550/dwd_weather/releases/tag/v2.0.0).
