### ISSUE TITLE
Additional Attributes in the forecast section. 

### ISSUE THREAD

**Issue by UdoD5** [FL550/dwd_weather#79]
Hi, 
not sure if i don't see it but i wasn't able to find any setting related to the display of the forecast. 
Beside the max and min Temp. I would like to display the sun hours per day, max. expected rainfall per day and max. Windspeeds per day.
Is that somehow already possible? 

<img width="374" alt="22-09-2023 17-21-53" src="https://github.com/FL550/dwd_weather/assets/125830597/8f799d72-0d4d-47df-8b23-b2a5bc9ca2b6">

**Comment by FL550** [comment]
Yes, this should be possible. However, this could probably only be done with a custom weather card.
