### ISSUE TITLE
"Nowcast"/interpolate current weather values

### ISSUE THREAD

**Issue by flxtr** [FL550/dwd_weather#81]
**Is your feature request related to a problem? Please describe.**

The values representing the current weather are up to one hour out of date and about a half hour in average.

Especially in the morning and evening weather often changes so fast that last hour's temperature might be 4-5K off or so.

**Describe the solution you'd like**

It would be great if there was an option, to kind of nowcast the current weather values.

For example one could linearly interpolate between the newest reported value (or forecast for the beginning of the current hour) and the forecast for the next hour.

**Describe alternatives you've considered**

Alternatively one could set the current value to next hour's forecast, if current time is greater than $current_hour and 30 minutes. That would lower the worst case to 30 min out of date.

**Additional context**

According to this comment I'm not the only one: https://github.com/FL550/dwd_weather/issues/57#issuecomment-1165641721 by @nikipore

The DWD Warn Wetter App selects automatically next hour's forecast at some point in time.
![dwd_screenshot](https://github.com/FL550/dwd_weather/assets/16322546/9b676d59-bec6-4f4b-b93a-47f0080ee013)

**Comment by FL550** [comment]
Thanks for reaching out and filling out the template.I'll add an option for this.

**Comment by FL550** [comment]
Included in new version v2.0.6.
