### ISSUE TITLE
Get nearest Station ID to latitude/longitude

### ISSUE THREAD

**Issue by GerdRuetten** [FL550/dwd_weather#84]
Example:
We drive next week in holiday and i will get the weather forecast for this point.
I know the lat/long but i don't now, how is the nearest DWD-Station to this point.

Nice feature is, to take the lat/long to configuration the forecats.

**Comment by GerdRuetten** [comment]
@FL550 

Thank you to flag it with the enhancement tag

**Comment by FL550** [comment]
Included in new version v2.0.6.

**Comment by GerdRuetten** [comment]
Wooow nice and good solution!

v2.0.7: Confirm! Location can be selected by a card and the integration suggests the nearest weather station to this location.
