### ISSUE TITLE
Problems with Better Thermostat summermode with Version 2.0.*

### ISSUE THREAD

**Issue by l-freund** [FL550/dwd_weather#88]
I'm using the DWD Integration together with Better Thermostat. When the current outside temperature reported by DWD is above a certain value, Better Thermostat turns off my radiators. For this the weahter entity, not the temperature sensor is used.
With version 2.0.* this summermode is always active despite the reported temperature beeing below the configured value. With 1.2.28 this works fine.
I can't really tell if this is an issue related to Better Thermostat or to the DWD Integration but since this only happens with the new version my guess is, the method of reporting outside temperature within the weather entity has changed and this could be an issue in other scenarios, too.

My Version of HA: 2023.9.3
My Version of Better Thermostat: 1.3.0

**Comment by FL550** [comment]
Hi, thanks for reaching out. The changes I made, were in line with the announcement from HA, so you have to address this to Better Thermostat.

**Comment by l-freund** [comment]
OK. Thank you! In this case I'll close this issue and try my luck over at Better Thermostat.
