### ISSUE TITLE
Forecast with force_hourly regularly unavaible — network error?

### ISSUE THREAD

**Issue by diplix** [FL550/dwd_weather#89]
since version **2.0.3** i see regular errors like this for my force_hourly dwd weather instance (6 hour forcast continues to work flawlessly — no unavailable sensors at any time).

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dwd_weather
Source: helpers/update_coordinator.py:290
Integration: Deutscher Wetterdienst (documentation, issues)
First occurred: 6. Oktober 2023 um 20:50:37 (9 occurrences)
Last logged: 05:31:20

Unexpected error fetching DWD Weather Coordinator for X104 data: '2023-10-16T23:00:00.000Z'
Unexpected error fetching DWD Weather Coordinator for X104 data: '2023-10-17T00:00:00.000Z'
Unexpected error fetching DWD Weather Coordinator for X104 data: '2023-10-17T01:00:00.000Z'
Unexpected error fetching DWD Weather Coordinator for X104 data: '2023-10-17T02:00:00.000Z'
Unexpected error fetching DWD Weather Coordinator for X104 data: '2023-10-17T03:00:00.000Z'
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/dwd_weather/connector.py", line 56, in async_update
    return await self._hass.async_add_executor_job(self._update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/dwd_weather/connector.py", line 63, in _update
    self.dwd_weather.update(
  File "/home/homeassistant/homeassistant_p3.11/lib/python3.11/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 579, in update
    self.forecast_data[item]["wwP"] = temp_forecast_data[item]["wwP"]
                                      ~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '2023-10-16T18:00:00.000Z'
```
sensors are „unavailable“ and recover aftre 5 minutes (next update). you can see those 5 minute „outages“ in history as well:
<img width="587" alt="image" src="https://github.com/FL550/dwd_weather/assets/4541494/5db2adc0-1662-49e8-a854-24b0a8503223">

i have a feeling it’s rather some kind of timeout / timing issue, rather than a network problem since the pattern is too regular.

**Comment by FL550** [comment]
Yes, it seems so. The reason for crash is a change I made to make the precipitation duration and precipitation probability available in hourly mode. Normally this error shouldn't occur, but as two network requests are done for this there might be a timing issue. It seems I need to handle this more gracefully. Thanks for reaching out!

**Comment by FL550** [comment]
Version v2.0.4 should fix this.

**Comment by nikipore** [comment]
Still same behavior in 2.0.4.

**Comment by diplix** [comment]
> Still same behavior in 2.0.4.

can confirm.

**Comment by FL550** [comment]
Hm, same log files also?

**Comment by FL550** [comment]
This error might be due to missing data points in the future. I can try to avoid this by checking how much date keys are available. I'll fix this tomorrow.

**Comment by FL550** [comment]
Hopefully the new version removes this error.

**Comment by diplix** [comment]
seems to work for me now, no unavailable sensors anymore. thanks!
i hope to find some time soon to make up to my promise to make some notes to the readme.

**Comment by FL550** [comment]
Glad to hear this! And thanks for the PR!
