### ISSUE TITLE
Wrong nightly icon for clear sky

### ISSUE THREAD

**Issue by Eyco1981** [FL550/dwd_weather#91]
**Is your feature request related to a problem? Please describe.**
A clear sky condition at night is shown as "sunny" (at least in the hourly forcast).
![dwd](https://github.com/FL550/dwd_weather/assets/88980079/8981a85c-2e9f-470d-88f9-b95a56bfc84e)

**Describe the solution you'd like**
Showing the icon "clear-night" during night hours, like this weather integration:
![alternative](https://github.com/FL550/dwd_weather/assets/88980079/b7d664a5-b1a7-4103-8940-ea3058f38f12)

**Comment by FL550** [comment]
Is implemented in 2.0.9

**Comment by Eyco1981** [comment]
It is still showing sunny at night with 2.0.9.
![weather](https://github.com/FL550/dwd_weather/assets/88980079/e908dd9e-2876-40d7-902c-5bd2afacd58c)

**Comment by Eyco1981** [comment]
Was able to see a bit more.
Later than midnight the clear-night symbol is shown.
But everything up to midnight still shows sunny.
The time period for clear-night might need some further adjustments.

**Comment by microraptor** [comment]
The right way to time it would be via the sunset/sunrise times for the selected station. If DWD doesn't provide that, perhaps it is best to pull it from a different API. Otherwise you could also use a [monthly table for Germany](https://sunrise.maplogs.com/germany.29.html) in general to approximate the times.

**Comment by Eyco1981** [comment]
Or at least a more plausible fixed time period. For example 8pm to 7am or something like that.

**Comment by FL550** [comment]
Thanks for the suggested solutions. As the weather data is provided for stations all over the world (I guess it's mainly used in Germany, but there are some stations used outside Germany), I have to find a solution which fits all.

**Comment by sevorl** [comment]
The "sun.sun" entity is available in home assistant out of the box. If "below horizon", show clear-night. 
If sun.sun is above horizon (or unavailable/unknown) show sunny.

**Comment by FL550** [comment]
> The "sun.sun" entity is available in home assistant out of the box. If "below horizon", show clear-night. If sun.sun is above horizon (or unavailable/unknown) show sunny.

But this will only work, if you select a station which is near your home.

**Comment by variada** [comment]
with 2.0.11 I get 'sunny' instead of 'clear-night' for 4 o'clock in the morning when it's definitely still pitch-black dark over here (earlier it's cloudy here, so can't really say for evening behaviour). see screenshot.

![image](https://github.com/FL550/dwd_weather/assets/83453466/d201053a-e021-4a24-a112-ef1965c5dc9b)

**Comment by Eyco1981** [comment]
Same here. At 3am it is sunny.

**Comment by Eyco1981** [comment]
![dwd](https://github.com/FL550/dwd_weather/assets/88980079/434476ed-948d-4922-a7e9-5d9476318a39)

**Comment by FL550** [comment]
Found the error. The arguments of lat and lon for the library were in an unexpected order, which led to false sunrise/sunset times. Should be fixed in 2.0.12

**Comment by sevorl** [comment]
Just wanted to say thanks again for this fix. 
Every time I see the clear-night icon now, I enjoy this!
