### ISSUE TITLE
v2.0.5: Duplicate weather stations

### ISSUE THREAD

**Issue by GerdRuetten** [FL550/dwd_weather#92]
## Version of home_assistant
Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

## Version of the custom_component
2.0.5

## Describe the bug
The listbox shows duplicate weather stations. One is wrong (the first in the following screenshot), one is correct (the second)

![image](https://github.com/FL550/dwd_weather/assets/97361636/b243057e-bc3c-43cd-8861-ddec5f358629)

## Debug log

```text

no log neccessary

```

**Comment by FL550** [comment]
You are always my tester, thank you very much for reaching out directly!

This is very strange, as I haven't changed the station list since the last update. I'll have to recheck this again.

**Comment by FL550** [comment]
Found the error. Will be fixed when I release the next version.

**Comment by FL550** [comment]
New version is out

**Comment by GerdRuetten** [comment]
Anytime! I think it's great that you care about integration so much

v2.0.7: Confirm! No more duplicate for "my" weatherstation

**Comment by FL550** [comment]
Thank you very much! It's in fact my first open source project that many people use, so I feel a bit responsible for it. Maybe a bit too much sometimes, as it requires a lot of my free time. Anyone who reaches out, and may it only be error reports, shows me, that the project is helpful for people 😊
