### ISSUE TITLE
Do not provide minimum temperature for hourly forecasts

### ISSUE THREAD

**Issue by microraptor** [FL550/dwd_weather#93]
Currently the integration provides max and min temperature values for daily and hourly forecasts. If I read the code correctly, the max and min of the hourly forecasts will always be the same. The HA native Met.no integration provides max and min for the daily forecasts, but only one temperature value for the hourly forecasts.

Providing only one temperature value for hourly forecasts also looks better on the native weather card.
DWD:
![image](https://github.com/FL550/dwd_weather/assets/15663536/56209130-1216-435c-92c5-66a8a1846d98)

Met.no:
![image](https://github.com/FL550/dwd_weather/assets/15663536/4ee3235b-4108-4ef9-a67c-9fe16399fbd8)

**Comment by FL550** [comment]
Included in new version v2.0.6.
