### ISSUE TITLE
v2.0.9: Translation/Localisation error in configuration dialog

### ISSUE THREAD

**Issue by GerdRuetten** [FL550/dwd_weather#96]
## Version of home_assistant

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

## Version of the custom_component

v2.0.9

## Describe the bug
There is a translation error in the configuration dialog if the standard language are german

<img width="629" alt="image" src="https://github.com/FL550/dwd_weather/assets/97361636/8276cd75-fc69-4e27-bd8b-d741de2ed18b">

## Debug log

```text

not necessary

```

**Comment by FL550** [comment]
Merci! Ich habe es angepasst. In der nächsten Version ist es behoben.
