### ISSUE TITLE
v2.0.9: Error in HA-log

### ISSUE THREAD

**Issue by GerdRuetten** [FL550/dwd_weather#97]
## Version of home_assistant

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

## Version of the custom_component

v2.0.9

## Describe the bug
Bug #94 has been fixed.
Thanks for that!
But now I get the following error in the HA log:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371
First occurred: 18:13:38 (1 occurrences)
Last logged: 18:13:38

Entity None (<class 'custom_components.dwd_weather.weather.DWDWeather'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please create a bug report at https://github.com/FL550/dwd_weather/issues

```

## Debug log

Do you need a full debug log?

**Comment by bbr111** [comment]
can confirm the error. same in my HA log
