### ISSUE TITLE
Previous precipitation sensors are missing

### ISSUE THREAD

**Issue by heinemannj** [FL550/dwd_weather#98]
I'm using the actual version provided by HASC.

Previous precipitation sensors are missing:

```
- sensor.precipitation_duration_raesfeld_ka (s/h)
- sensor.precipitation_probability_raesfeld_ka (%)
```

**Comment by FL550** [comment]
Without any information about the relevant station or debug log files, I am unable to help.

**Comment by heinemannj** [comment]
Ohh - yes - Sorry

```
Station H316: Raesfeld Ka
by DWD Weather
```

[home-assistant_dwd_weather_2023-10-23T10-03-00.946Z.log](https://github.com/FL550/dwd_weather/files/13068783/home-assistant_dwd_weather_2023-10-23T10-03-00.946Z.log)

**Comment by diplix** [comment]
if you activate the option for hourly updates, DWD does not provide data for precipitation duration and probability. if the data is not available, this component does not create sensors for it. as a workaround you can create an instance with the same station withput activating the hourly updates option and use the slightly less acurate sensor data that is refreshed twice daily.

**Comment by heinemannj** [comment]
> if you activate the option for hourly updates, DWD does not provide data for precipitation duration and probability. if the data is not available, this component does not create sensors for it. as a workaround you can create an instance with the same station withput activating the hourly updates option and use the slightly less acurate sensor data that is refreshed twice daily.

Jepp, you are absolutely right -This is my solution:

![image](https://github.com/FL550/dwd_weather/assets/3251642/89d876e3-258d-4ec9-a243-8d2f30b809aa)

You feedback is really appreciated!
Many thanks!

Note:
All other sensors provide hourly updates, only the precipitation duration and probability sensors have limitations ... - strange ...

**Comment by heinemannj** [comment]
A short note in your dokumentation might be helpful.

**Comment by diplix** [comment]
> A short note in your dokumentation might be helpful.

done in #101.
